import type { Metadata } from 'next'
import Link from 'next/link'
import { generateSampleDigest } from '@/lib/sampleDigest'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'

export const dynamic = 'force-dynamic'

type LeadPreviewPageProps = {
  params: Promise<{ id: string }>
}

function decodeLeadId(id: string): string {
  const trimmed = decodeURIComponent(id).trim()
  if (trimmed.length === 0) return 'acme.com'
  return trimmed.replace(/[-_]+/g, ' ').slice(0, 80)
}

export async function generateMetadata({ params }: LeadPreviewPageProps): Promise<Metadata> {
  const { id } = await params
  const companySeed = decodeLeadId(id)
  return {
    title: `${companySeed} lead preview | LeadIntel`,
    description: 'Shared lead preview showing score, timing signal, and sample outreach.',
    alternates: {
      canonical: `https://raelinfo.com/public/lead-preview/${encodeURIComponent(id)}`,
    },
    openGraph: {
      title: `${companySeed} lead preview | LeadIntel`,
      description: 'Score, why-now signal, and outreach sample from LeadIntel.',
      url: `https://raelinfo.com/public/lead-preview/${encodeURIComponent(id)}`,
    },
  }
}

export default async function PublicLeadPreviewPage({ params }: LeadPreviewPageProps) {
  const { id } = await params
  const companySeed = decodeLeadId(id)
  const sample = generateSampleDigest(companySeed)

  return (
    <div className="min-h-screen bg-background terminal-grid">
      <div className="container mx-auto max-w-3xl px-4 py-10 space-y-6">
        <header className="space-y-2">
          <Badge variant="outline" className="border-cyan-500/20 bg-cyan-500/10 text-cyan-200">
            Public lead preview
          </Badge>
          <h1 className="text-2xl font-bold">Shared lead result</h1>
          <p className="text-sm text-muted-foreground">
            Generated by raelinfo.com
          </p>
        </header>

        <Card className="border-cyan-500/20 bg-card/60">
          <CardHeader className="pb-3">
            <div className="flex items-center justify-between gap-2">
              <CardTitle className="text-xl">{sample.company}</CardTitle>
              <Badge className="bg-cyan-500/10 text-cyan-200 border-cyan-500/20">{sample.score}/100</Badge>
            </div>
            <CardDescription>Lead timing snapshot</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div>
              <div className="text-xs uppercase tracking-wide text-muted-foreground">Why now</div>
              <p className="mt-1 text-sm text-foreground">{sample.whyNow}</p>
            </div>
            <div className="rounded border border-cyan-500/10 bg-background/40 p-3">
              <div className="text-xs uppercase tracking-wide text-muted-foreground">Sample outreach</div>
              {sample.outreach.subject ? (
                <div className="mt-2 text-sm text-foreground">
                  <span className="font-medium">Subject:</span> {sample.outreach.subject}
                </div>
              ) : null}
              <p className="mt-2 text-sm text-muted-foreground whitespace-pre-wrap">{sample.outreach.body}</p>
            </div>
            <Button asChild className="neon-border hover:glow-effect">
              <Link href="/demo">Generate your own leads</Link>
            </Button>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
