import { escapeHtml } from '@/lib/email/templates'
import { serverEnv } from '@/lib/env'

export type AdminNotificationEmail = { subject: string; html: string; text: string }

function stableVariantIndex(seed: string | undefined, count: number): number {
  if (count <= 1) return 0
  const input = (seed ?? '').trim()
  if (!input) return 0
  let hash = 2166136261
  for (let i = 0; i < input.length; i += 1) {
    hash ^= input.charCodeAt(i)
    hash += (hash << 1) + (hash << 4) + (hash << 7) + (hash << 8) + (hash << 24)
  }
  return Math.abs(hash >>> 0) % count
}

function pickVariant(seed: string | undefined, values: readonly string[]): string {
  return values[stableVariantIndex(seed, values.length)] ?? values[0] ?? ''
}

const INTERNAL_VARIANTS = [
  'Operator note: reviewed and generated by LeadIntel automation.',
  'Operator note: summary generated from privacy-safe operational signals.',
  'Operator note: use this as a quick review handoff.',
] as const

function mono(text: string): string {
  return `<pre style="white-space: pre-wrap; background:#0b1220; color:#e5e7eb; border:1px solid rgba(148,163,184,0.25); padding:14px; border-radius:10px;">${escapeHtml(
    text
  )}</pre>`
}

export function renderAdminNotificationEmail(args: {
  title: string
  lines: string[]
  appUrl: string
  ctaHref?: string
  ctaLabel?: string
  variationSeed?: string
}): AdminNotificationEmail {
  const subject = `LeadIntel · ${args.title}`
  const variant = pickVariant(args.variationSeed, INTERNAL_VARIANTS)
  const body = [...args.lines, '', variant].join('\n')
  const ctaHref = args.ctaHref ? args.ctaHref : `${args.appUrl}/admin/ops`
  const ctaLabel = args.ctaLabel ? args.ctaLabel : 'Open ops'
  const logo = (() => {
    const raw = (serverEnv.EMAIL_BRAND_IMAGE_URL ?? '').trim()
    if (!raw) return null
    try {
      const u = new URL(raw)
      return u.protocol === 'https:' ? u.toString() : null
    } catch {
      return null
    }
  })()
  const header = logo
    ? `<div style="margin-bottom:10px;">
        <a href="${escapeHtml(args.appUrl)}" style="text-decoration:none;">
          <img src="${escapeHtml(logo)}" alt="LeadIntel logo" style="max-width:190px;height:auto;border:0;display:block;">
        </a>
      </div>`
    : '<div style="font-size:12px;color:#94a3b8;letter-spacing:0.12em;text-transform:uppercase;">LeadIntel operator notification</div>'

  const text = [subject, '', body, '', `Open: ${ctaHref}`].join('\n')
  const html = `<!doctype html><html><body style="margin:0;padding:24px;background:#050a14;color:#e5e7eb;font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial;">
    <div style="max-width:640px;margin:0 auto;">
      ${header}
      <h1 style="margin:10px 0 0 0;font-size:18px;color:#e5e7eb;">${escapeHtml(args.title)}</h1>
      <div style="margin-top:12px;">${mono(body)}</div>
      <div style="margin-top:14px;">
        <a href="${escapeHtml(ctaHref)}" style="display:inline-block; padding:10px 14px; border-radius:10px; text-decoration:none; font-weight:700; background:rgba(34,211,238,0.18); color:#67e8f9; border:1px solid rgba(34,211,238,0.35);">
          ${escapeHtml(ctaLabel)}
        </a>
      </div>
    </div>
  </body></html>`

  return { subject, html, text }
}

