'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { createClient } from '@/lib/supabase/client'
import { track } from '@/lib/analytics'

type ResponseStatus = 'not sent' | 'sent' | 'replied' | 'interested' | 'booked' | 'closed' | 'not interested'
type TemplateKey = 'initial' | 'followup1' | 'followup2'

type LeadRow = {
  id: string
  company_name: string | null
  company_domain: string | null
  company_url: string | null
  prospect_email: string | null
  ai_personalized_pitch: string | null
  created_at: string | null
}

type TriggerRow = {
  lead_id: string | null
  event_type: string | null
  headline: string | null
  event_description: string | null
  detected_at: string | null
  created_at: string | null
}

type OutboundLead = {
  id: string
  companyName: string
  companyDomain: string | null
  prospectEmail: string | null
  fitScore: number
  industry: string
  role: string
  hasHiringSignal: boolean
  whyNow: string
  generatedMessage: string
  primaryTrigger: string
  whyThisLead: string[]
  createdAt: string
}

const STATUS_STORAGE_KEY = 'leadintel-outbound-response-status-v2'
const MESSAGE_STORAGE_KEY = 'leadintel-outbound-message-drafts-v2'
const DAILY_SEND_GOAL = 20
const TEMPLATE_OPTIONS: ReadonlyArray<{ key: TemplateKey; label: string }> = [
  { key: 'initial', label: 'Initial outreach' },
  { key: 'followup1', label: 'Follow-up #1' },
  { key: 'followup2', label: 'Follow-up #2' },
]
const RESPONSE_STATUS_OPTIONS: ReadonlyArray<ResponseStatus> = [
  'not sent',
  'sent',
  'replied',
  'interested',
  'booked',
  'closed',
  'not interested',
]
const SENT_LIKE_STATUSES = new Set<ResponseStatus>(['sent', 'replied', 'interested', 'booked', 'closed', 'not interested'])
const REPLY_LIKE_STATUSES = new Set<ResponseStatus>(['replied', 'interested', 'booked', 'closed'])

function parseFitScore(draft: string | null): number {
  if (!draft) return 0
  const matched = draft.match(/^\[LeadIntel Fit (\d{1,3})\/100\]/)
  const score = matched ? Number.parseInt(matched[1], 10) : 0
  if (!Number.isFinite(score)) return 0
  return Math.max(0, Math.min(100, score))
}

function parseField(draft: string | null, label: string): string {
  if (!draft) return 'Unknown'
  const regex = new RegExp(`^${label}:\\s*(.+)$`, 'im')
  const matched = draft.match(regex)
  const value = matched?.[1]?.trim()
  return value && value.length > 0 ? value : 'Unknown'
}

function parseWhyNow(draft: string | null): string {
  if (!draft) return 'Recent signals suggest strong timing.'
  const firstLine = draft.split('\n')[0] ?? ''
  const matched = firstLine.match(/^\[LeadIntel Fit \d{1,3}\/100\]\s*(.+)$/)
  if (matched?.[1]?.trim()) return matched[1].trim()
  return 'Recent signals suggest strong timing.'
}

function parseGeneratedMessage(draft: string | null, companyName: string): string {
  if (!draft) {
    return `Hi ${companyName} team,\n\nNoticed recent momentum and wanted to share a quick idea.\n\nGenerated by raelinfo.com`
  }
  const lines = draft
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.length > 0 && !line.startsWith('[LeadIntel Fit '))
  if (lines.length === 0) {
    return `Hi ${companyName} team,\n\nNoticed recent momentum and wanted to share a quick idea.\n\nGenerated by raelinfo.com`
  }
  return `${lines.join('\n')}\n\nGenerated by raelinfo.com`
}

function isHiringSignal(trigger: TriggerRow | null): boolean {
  if (!trigger) return false
  const haystack = `${trigger.event_type ?? ''} ${trigger.headline ?? ''} ${trigger.event_description ?? ''}`.toLowerCase()
  return haystack.includes('hiring') || haystack.includes('hire') || haystack.includes('new role')
}

function classifyTriggerSignal(trigger: TriggerRow): 'hiring signal' | 'expansion signal' | 'funding/growth signal' | null {
  const haystack = `${trigger.event_type ?? ''} ${trigger.headline ?? ''} ${trigger.event_description ?? ''}`.toLowerCase()
  if (haystack.includes('hiring') || haystack.includes('hire') || haystack.includes('new role') || haystack.includes('headcount')) {
    return 'hiring signal'
  }
  if (
    haystack.includes('expansion')
    || haystack.includes('new market')
    || haystack.includes('new region')
    || haystack.includes('office')
    || haystack.includes('launch')
    || haystack.includes('partnership')
  ) {
    return 'expansion signal'
  }
  if (
    haystack.includes('funding')
    || haystack.includes('raised')
    || haystack.includes('series ')
    || haystack.includes('growth')
    || haystack.includes('revenue')
    || haystack.includes('acquisition')
    || haystack.includes('investment')
  ) {
    return 'funding/growth signal'
  }
  return null
}

function summarizeTrigger(trigger: TriggerRow | null): string {
  if (!trigger) return 'showing fresh buying signals'
  const preferred = trigger.headline?.trim() || trigger.event_description?.trim() || trigger.event_type?.trim()
  if (!preferred) return 'showing fresh buying signals'
  return preferred.length > 120 ? `${preferred.slice(0, 117)}...` : preferred
}

function buildWhyThisLead(args: {
  triggerRows: TriggerRow[]
  role: string
  industry: string
  companyName: string
}): string[] {
  const categories = new Set<string>()
  for (const trigger of args.triggerRows) {
    const category = classifyTriggerSignal(trigger)
    if (category) categories.add(category)
  }
  return [
    categories.has('hiring signal')
      ? 'Hiring signal: team growth or role expansion is active.'
      : 'Hiring signal: no recent hiring trigger detected yet.',
    categories.has('expansion signal')
      ? 'Expansion signal: new market/product/partnership activity is visible.'
      : 'Expansion signal: no recent expansion trigger detected yet.',
    categories.has('funding/growth signal')
      ? 'Funding/growth signal: momentum and budget window may be open.'
      : 'Funding/growth signal: no recent funding/growth trigger detected yet.',
    `Role/company fit: ${args.role} in ${args.industry} at ${args.companyName}.`,
  ]
}

function buildTemplateMessage(lead: OutboundLead, templateKey: TemplateKey): string {
  const trigger = lead.primaryTrigger
  if (templateKey === 'initial') {
    return [
      `Hey - noticed ${lead.companyName} is ${trigger}.`,
      '',
      'Teams at this stage usually need more qualified pipeline without more manual research.',
      '',
      'I built LeadIntel to find high-intent leads and write outreach daily.',
      '',
      'Worth seeing 5 leads for your business?',
    ].join('\n')
  }
  if (templateKey === 'followup1') {
    return [
      `Quick follow-up - I can show you a short lead list for ${lead.companyName} so you can judge if it's useful.`,
      '',
      'Worth seeing 5 leads for your business?',
    ].join('\n')
  }
  return [
    'Should I close this out, or would seeing 5 fresh leads for your market be useful?',
    '',
    'Worth seeing 5 leads for your business?',
  ].join('\n')
}

function draftKey(leadId: string, templateKey: TemplateKey): string {
  return `${leadId}:${templateKey}`
}

function todayDateKey(): string {
  return new Date().toISOString().slice(0, 10)
}

export function OutboundExecutionPanel() {
  const supabase = createClient()
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [query, setQuery] = useState('')
  const [leads, setLeads] = useState<OutboundLead[]>([])
  const [industryFilter, setIndustryFilter] = useState('all')
  const [roleFilter, setRoleFilter] = useState('all')
  const [hiringFilter, setHiringFilter] = useState<'all' | 'hiring'>('all')
  const [selectedLeadIds, setSelectedLeadIds] = useState<Set<string>>(new Set())
  const [activeLeadId, setActiveLeadId] = useState<string | null>(null)
  const [activeTemplate, setActiveTemplate] = useState<TemplateKey>('initial')
  const [messageDrafts, setMessageDrafts] = useState<Record<string, string>>({})
  const [responseStatuses, setResponseStatuses] = useState<Record<string, ResponseStatus>>({})
  const [copied, setCopied] = useState(false)

  const loadOutboundLeads = useCallback(async () => {
    setLoading(true)
    setError(null)
    try {
      const {
        data: { user },
      } = await supabase.auth.getUser()
      if (!user) {
        setLeads([])
        return
      }

      const { data: leadRowsRaw, error: leadError } = await supabase
        .from('leads')
        .select('id, company_name, company_domain, company_url, prospect_email, ai_personalized_pitch, created_at')
        .eq('user_id', user.id)
        .order('created_at', { ascending: false })
        .limit(200)

      if (leadError) throw leadError
      const leadRows = (leadRowsRaw ?? []) as LeadRow[]
      const leadIds = leadRows.map((row) => row.id)

      let triggerRows: TriggerRow[] = []
      if (leadIds.length > 0) {
        const { data: triggerRowsRaw } = await supabase
          .from('trigger_events')
          .select('lead_id, event_type, headline, event_description, detected_at, created_at')
          .eq('user_id', user.id)
          .in('lead_id', leadIds)
          .order('detected_at', { ascending: false })
          .limit(500)
        triggerRows = (triggerRowsRaw ?? []) as TriggerRow[]
      }

      const triggerRowsByLead = new Map<string, TriggerRow[]>()
      for (const row of triggerRows) {
        if (!row.lead_id) continue
        const current = triggerRowsByLead.get(row.lead_id) ?? []
        current.push(row)
        triggerRowsByLead.set(row.lead_id, current)
      }

      const mapped = leadRows.map((row) => {
        const leadTriggers = triggerRowsByLead.get(row.id) ?? []
        const trigger = leadTriggers[0] ?? null
        const companyName = row.company_name ?? row.company_domain ?? row.company_url ?? 'Unknown company'
        const role = parseField(row.ai_personalized_pitch, 'Target role')
        const industry = parseField(row.ai_personalized_pitch, 'Industry')
        return {
          id: row.id,
          companyName,
          companyDomain: row.company_domain ?? null,
          prospectEmail: row.prospect_email ?? null,
          fitScore: parseFitScore(row.ai_personalized_pitch),
          industry,
          role,
          hasHiringSignal: isHiringSignal(trigger),
          whyNow: parseWhyNow(row.ai_personalized_pitch),
          generatedMessage: parseGeneratedMessage(row.ai_personalized_pitch, companyName),
          primaryTrigger: summarizeTrigger(trigger),
          whyThisLead: buildWhyThisLead({
            triggerRows: leadTriggers,
            role,
            industry,
            companyName,
          }),
          createdAt: row.created_at ?? new Date().toISOString(),
        } satisfies OutboundLead
      })

      mapped.sort((a, b) => b.fitScore - a.fitScore || b.createdAt.localeCompare(a.createdAt))
      setLeads(mapped)
      setActiveLeadId((current) => current ?? mapped[0]?.id ?? null)
      track('outbound_execution_loaded', { count: mapped.length })
    } catch {
      setError('Failed to load leads for outbound execution.')
      setLeads([])
    } finally {
      setLoading(false)
    }
  }, [supabase])

  useEffect(() => {
    void loadOutboundLeads()
  }, [loadOutboundLeads])

  useEffect(() => {
    if (typeof window === 'undefined') return
    try {
      const rawStatus = window.localStorage.getItem(STATUS_STORAGE_KEY)
      if (rawStatus) {
        const parsed = JSON.parse(rawStatus) as Record<string, ResponseStatus>
        setResponseStatuses(parsed)
      }
    } catch {
      setResponseStatuses({})
    }
    try {
      const rawDrafts = window.localStorage.getItem(MESSAGE_STORAGE_KEY)
      if (rawDrafts) {
        const parsed = JSON.parse(rawDrafts) as Record<string, string>
        setMessageDrafts(parsed)
      }
    } catch {
      setMessageDrafts({})
    }
  }, [])

  useEffect(() => {
    if (typeof window === 'undefined') return
    window.localStorage.setItem(STATUS_STORAGE_KEY, JSON.stringify(responseStatuses))
  }, [responseStatuses])

  useEffect(() => {
    if (typeof window === 'undefined') return
    window.localStorage.setItem(MESSAGE_STORAGE_KEY, JSON.stringify(messageDrafts))
  }, [messageDrafts])

  const industries = useMemo(() => {
    const values = Array.from(new Set(leads.map((lead) => lead.industry).filter((value) => value !== 'Unknown')))
    values.sort((a, b) => a.localeCompare(b))
    return values
  }, [leads])

  const roles = useMemo(() => {
    const values = Array.from(new Set(leads.map((lead) => lead.role).filter((value) => value !== 'Unknown')))
    values.sort((a, b) => a.localeCompare(b))
    return values
  }, [leads])

  const filteredLeads = useMemo(() => {
    const search = query.trim().toLowerCase()
    return leads.filter((lead) => {
      const matchesSearch =
        search.length === 0
        || lead.companyName.toLowerCase().includes(search)
        || (lead.companyDomain ?? '').toLowerCase().includes(search)
      const matchesIndustry = industryFilter === 'all' || lead.industry === industryFilter
      const matchesRole = roleFilter === 'all' || lead.role === roleFilter
      const matchesHiring = hiringFilter === 'all' || lead.hasHiringSignal
      return matchesSearch && matchesIndustry && matchesRole && matchesHiring
    })
  }, [hiringFilter, industryFilter, leads, query, roleFilter])

  const todaysLeadsCount = useMemo(() => {
    const today = todayDateKey()
    return leads.filter((lead) => lead.createdAt.slice(0, 10) === today).length
  }, [leads])

  const activeLead = useMemo(
    () => filteredLeads.find((lead) => lead.id === activeLeadId) ?? filteredLeads[0] ?? null,
    [activeLeadId, filteredLeads]
  )

  const activeDraftKey = useMemo(() => (activeLead ? draftKey(activeLead.id, activeTemplate) : null), [activeLead, activeTemplate])

  const activeMessage = useMemo(() => {
    if (!activeLead) return ''
    if (!activeDraftKey) return ''
    return messageDrafts[activeDraftKey] ?? buildTemplateMessage(activeLead, activeTemplate)
  }, [activeDraftKey, activeLead, activeTemplate, messageDrafts])

  useEffect(() => {
    if (!activeLead || !activeDraftKey) return
    setMessageDrafts((current) => {
      if (current[activeDraftKey]) return current
      return {
        ...current,
        [activeDraftKey]: buildTemplateMessage(activeLead, activeTemplate),
      }
    })
  }, [activeDraftKey, activeLead, activeTemplate])

  const todaysSentCount = useMemo(() => {
    return leads.filter((lead) => SENT_LIKE_STATUSES.has(responseStatuses[lead.id] ?? 'not sent')).length
  }, [leads, responseStatuses])

  const weeklyInsights = useMemo(() => {
    let sent = 0
    let replies = 0
    let interested = 0
    let booked = 0
    let closed = 0
    for (const lead of leads) {
      const status = responseStatuses[lead.id] ?? 'not sent'
      if (SENT_LIKE_STATUSES.has(status)) sent += 1
      if (REPLY_LIKE_STATUSES.has(status)) replies += 1
      if (status === 'interested') interested += 1
      if (status === 'booked') booked += 1
      if (status === 'closed') closed += 1
    }
    const replyRate = sent > 0 ? Math.round((replies / sent) * 1000) / 10 : 0
    return { sent, replies, interested, booked, closed, replyRate }
  }, [leads, responseStatuses])

  function toggleSelected(leadId: string, checked: boolean): void {
    setSelectedLeadIds((current) => {
      const next = new Set(current)
      if (checked) next.add(leadId)
      else next.delete(leadId)
      return next
    })
  }

  function selectTopLeads(): void {
    const topIds = filteredLeads.slice(0, 10).map((lead) => lead.id)
    setSelectedLeadIds(new Set(topIds))
  }

  function exportSelectedLeads(): void {
    const selected = filteredLeads.filter((lead) => selectedLeadIds.has(lead.id))
    if (selected.length === 0) return

    const csv = [
      [
        'company',
        'domain',
        'email',
        'fit_score',
        'industry',
        'role',
        'hiring_signal',
        'response_status',
        'outreach_message',
        'attribution',
      ].join(','),
      ...selected.map((lead) => {
        const message = (messageDrafts[draftKey(lead.id, 'initial')] ?? lead.generatedMessage).replaceAll('"', '""')
        const status = responseStatuses[lead.id] ?? ''
        return [
          `"${lead.companyName.replaceAll('"', '""')}"`,
          `"${(lead.companyDomain ?? '').replaceAll('"', '""')}"`,
          `"${(lead.prospectEmail ?? '').replaceAll('"', '""')}"`,
          `"${lead.fitScore}"`,
          `"${lead.industry.replaceAll('"', '""')}"`,
          `"${lead.role.replaceAll('"', '""')}"`,
          `"${lead.hasHiringSignal ? 'yes' : 'no'}"`,
          `"${status}"`,
          `"${message}"`,
          '"Generated by raelinfo.com"',
        ].join(',')
      }),
    ].join('\n')

    const blob = new Blob([csv], { type: 'text/csv' })
    const url = window.URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `daily-outreach-${todayDateKey()}.csv`
    link.click()
    window.URL.revokeObjectURL(url)
    track('outbound_daily_exported', { count: selected.length })
  }

  async function copyTemplateMessage(templateKey: TemplateKey): Promise<void> {
    if (!activeLead) return
    const key = draftKey(activeLead.id, templateKey)
    const templateText = messageDrafts[key] ?? buildTemplateMessage(activeLead, templateKey)
    const text = `${templateText}\n\nGenerated by raelinfo.com`
    try {
      await navigator.clipboard.writeText(text)
      setCopied(true)
      window.setTimeout(() => setCopied(false), 1200)
      track('outbound_message_copied', { leadId: activeLead.id, template: templateKey })
    } catch {
      setCopied(false)
    }
  }

  function openActiveMessageInEmailClient(): void {
    if (!activeLead) return
    const subjectLabel =
      activeTemplate === 'initial' ? 'Initial outreach' : activeTemplate === 'followup1' ? 'Follow-up #1' : 'Follow-up #2'
    const subject = encodeURIComponent(`${subjectLabel} for ${activeLead.companyName}`)
    const body = encodeURIComponent(`${activeMessage}\n\nGenerated by raelinfo.com`)
    const recipient = activeLead.prospectEmail ?? ''
    window.location.href = `mailto:${recipient}?subject=${subject}&body=${body}`
    track('outbound_message_sent_intent', { leadId: activeLead.id, template: activeTemplate })
  }

  return (
    <Card className="border-cyan-500/20 bg-card/50">
      <CardHeader className="pb-3">
        <div className="flex flex-wrap items-center justify-between gap-2">
          <CardTitle className="text-base">Outbound execution loop</CardTitle>
          <Badge variant="outline">Today&apos;s Leads: {todaysLeadsCount} - Updated today</Badge>
        </div>
        <div className="text-xs text-muted-foreground">Generate - Select - Send - Track - Iterate</div>
      </CardHeader>
      <CardContent className="space-y-4">
        {error ? (
          <div className="rounded border border-red-500/20 bg-red-500/5 p-3 text-xs text-red-300">{error}</div>
        ) : null}

        <div className="rounded border border-cyan-500/20 bg-cyan-500/5 p-3">
          <div className="flex flex-wrap items-center justify-between gap-2">
            <div className="text-sm font-medium text-foreground">Today&apos;s goal: send {DAILY_SEND_GOAL} messages</div>
            <Badge variant="outline">
              {todaysSentCount}/{DAILY_SEND_GOAL}
            </Badge>
          </div>
          <div className="mt-2 h-2 rounded bg-cyan-500/10 overflow-hidden">
            <div
              className="h-full bg-cyan-400/70 transition-all"
              style={{ width: `${Math.min(100, Math.round((todaysSentCount / DAILY_SEND_GOAL) * 100))}%` }}
            />
          </div>
          <div className="mt-2 text-xs text-muted-foreground">Progress is based on leads marked sent (local status tracking).</div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-5 gap-3">
          <Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search company/domain" className="lg:col-span-2" />
          <select
            value={hiringFilter}
            onChange={(event) => setHiringFilter(event.target.value === 'hiring' ? 'hiring' : 'all')}
            className="h-10 rounded-md border border-input bg-background px-3 text-sm"
          >
            <option value="all">All signals</option>
            <option value="hiring">Hiring signals</option>
          </select>
          <select
            value={industryFilter}
            onChange={(event) => setIndustryFilter(event.target.value)}
            className="h-10 rounded-md border border-input bg-background px-3 text-sm"
          >
            <option value="all">All industries</option>
            {industries.map((industry) => (
              <option key={industry} value={industry}>
                {industry}
              </option>
            ))}
          </select>
          <select
            value={roleFilter}
            onChange={(event) => setRoleFilter(event.target.value)}
            className="h-10 rounded-md border border-input bg-background px-3 text-sm"
          >
            <option value="all">All roles</option>
            {roles.map((role) => (
              <option key={role} value={role}>
                {role}
              </option>
            ))}
          </select>
        </div>

        <div className="flex flex-wrap gap-2">
          <Button type="button" size="sm" variant="outline" onClick={selectTopLeads} disabled={loading || filteredLeads.length === 0}>
            Select top 10
          </Button>
          <Button type="button" size="sm" className="neon-border hover:glow-effect" onClick={exportSelectedLeads} disabled={selectedLeadIds.size === 0}>
            Export selected leads
          </Button>
          <Badge variant="outline">{selectedLeadIds.size} selected</Badge>
          <Badge variant="outline">These leads update daily</Badge>
        </div>

        <div className="grid grid-cols-1 xl:grid-cols-2 gap-4">
          <div className="rounded border border-cyan-500/10 bg-background/40 p-3 space-y-2 max-h-[420px] overflow-y-auto">
            {filteredLeads.length === 0 ? (
              <div className="text-xs text-muted-foreground">No leads match current ICP filters.</div>
            ) : (
              filteredLeads.slice(0, 40).map((lead) => {
                const status = responseStatuses[lead.id] ?? 'not sent'
                return (
                  <div
                    key={lead.id}
                    className={`rounded border p-2 ${activeLead?.id === lead.id ? 'border-cyan-500/30 bg-cyan-500/5' : 'border-cyan-500/10 bg-background/50'}`}
                  >
                    <div className="flex items-start justify-between gap-2">
                      <label className="flex items-start gap-2 min-w-0">
                        <input
                          type="checkbox"
                          checked={selectedLeadIds.has(lead.id)}
                          onChange={(event) => toggleSelected(lead.id, event.target.checked)}
                          className="mt-1"
                        />
                        <button type="button" className="min-w-0 text-left" onClick={() => setActiveLeadId(lead.id)}>
                          <div className="text-sm font-medium text-foreground truncate">{lead.companyName}</div>
                          <div className="text-[11px] text-muted-foreground truncate">
                            {lead.companyDomain ?? 'no domain'} - Fit {lead.fitScore}/100
                          </div>
                        </button>
                      </label>
                      <Badge variant="outline">{status}</Badge>
                    </div>
                    <div className="mt-2 flex flex-wrap gap-1">
                      <Badge variant="outline">{lead.industry}</Badge>
                      <Badge variant="outline">{lead.role}</Badge>
                      {lead.hasHiringSignal ? <Badge className="bg-emerald-500/10 text-emerald-200 border-emerald-500/20">Hiring</Badge> : null}
                    </div>
                  </div>
                )
              })
            )}
          </div>

          <div className="rounded border border-cyan-500/10 bg-background/40 p-3 space-y-3">
            {activeLead ? (
              <>
                <div>
                  <div className="text-sm font-medium text-foreground">{activeLead.companyName}</div>
                  <div className="text-xs text-muted-foreground mt-1">{activeLead.whyNow}</div>
                </div>
                <div className="rounded border border-cyan-500/10 bg-background/40 p-3 space-y-2">
                  <div className="text-xs uppercase tracking-wide text-muted-foreground">Why this lead</div>
                  <div className="text-xs text-foreground">Trigger: {activeLead.primaryTrigger}</div>
                  <ul className="list-disc pl-5 text-xs text-muted-foreground space-y-1">
                    {activeLead.whyThisLead.map((reason) => (
                      <li key={reason}>{reason}</li>
                    ))}
                  </ul>
                </div>
                <div className="space-y-2">
                  <div className="text-xs uppercase tracking-wide text-muted-foreground">Message templates</div>
                  <div className="flex flex-wrap gap-2">
                    {TEMPLATE_OPTIONS.map((template) => (
                      <Button
                        key={template.key}
                        type="button"
                        size="sm"
                        variant={activeTemplate === template.key ? 'default' : 'outline'}
                        onClick={() => setActiveTemplate(template.key)}
                      >
                        {template.label}
                      </Button>
                    ))}
                  </div>
                </div>
                <div className="space-y-2">
                  <div className="text-xs uppercase tracking-wide text-muted-foreground">Outreach view</div>
                  <Textarea
                    value={activeMessage}
                    onChange={(event) =>
                      setMessageDrafts((current) => ({
                        ...current,
                        [draftKey(activeLead.id, activeTemplate)]: event.target.value,
                      }))
                    }
                    className="min-h-[180px]"
                  />
                </div>
                <div className="flex flex-wrap gap-2">
                  <Button type="button" variant="outline" onClick={() => void copyTemplateMessage('initial')}>
                    {copied ? 'Copied' : 'Copy initial message'}
                  </Button>
                  <Button type="button" variant="outline" onClick={() => void copyTemplateMessage('followup1')}>
                    Copy follow-up #1
                  </Button>
                  <Button type="button" variant="outline" onClick={() => void copyTemplateMessage('followup2')}>
                    Copy follow-up #2
                  </Button>
                  <Button type="button" className="neon-border hover:glow-effect" onClick={openActiveMessageInEmailClient}>
                    Open email draft
                  </Button>
                </div>
                <div className="space-y-2">
                  <div className="text-xs uppercase tracking-wide text-muted-foreground">Response tracking</div>
                  <div className="flex flex-wrap gap-2">
                    {RESPONSE_STATUS_OPTIONS.map((status) => (
                      <Button
                        key={status}
                        type="button"
                        size="sm"
                        variant={(responseStatuses[activeLead.id] ?? 'not sent') === status ? 'default' : 'outline'}
                        onClick={() => {
                          setResponseStatuses((current) => ({ ...current, [activeLead.id]: status }))
                          track('outbound_response_status_changed', { leadId: activeLead.id, status })
                        }}
                      >
                        {status}
                      </Button>
                    ))}
                  </div>
                </div>
              </>
            ) : (
              <div className="text-xs text-muted-foreground">Select a lead to open outreach view.</div>
            )}
          </div>
        </div>

        <div className="grid grid-cols-1 xl:grid-cols-2 gap-4">
          <div className="rounded border border-cyan-500/20 bg-card/30 p-3 space-y-3">
            <div className="text-sm font-medium text-foreground">Weekly learning loop</div>
            <div className="grid grid-cols-2 md:grid-cols-3 gap-2 text-xs">
              <div className="rounded border border-cyan-500/10 bg-background/40 p-2">
                <div className="text-muted-foreground">Messages sent</div>
                <div className="text-foreground font-medium">{weeklyInsights.sent}</div>
              </div>
              <div className="rounded border border-cyan-500/10 bg-background/40 p-2">
                <div className="text-muted-foreground">Replies</div>
                <div className="text-foreground font-medium">{weeklyInsights.replies}</div>
              </div>
              <div className="rounded border border-cyan-500/10 bg-background/40 p-2">
                <div className="text-muted-foreground">Interested</div>
                <div className="text-foreground font-medium">{weeklyInsights.interested}</div>
              </div>
              <div className="rounded border border-cyan-500/10 bg-background/40 p-2">
                <div className="text-muted-foreground">Booked</div>
                <div className="text-foreground font-medium">{weeklyInsights.booked}</div>
              </div>
              <div className="rounded border border-cyan-500/10 bg-background/40 p-2">
                <div className="text-muted-foreground">Closed</div>
                <div className="text-foreground font-medium">{weeklyInsights.closed}</div>
              </div>
              <div className="rounded border border-cyan-500/10 bg-background/40 p-2">
                <div className="text-muted-foreground">Reply rate</div>
                <div className="text-foreground font-medium">{weeklyInsights.replyRate}%</div>
              </div>
            </div>
          </div>

          <div className="rounded border border-cyan-500/20 bg-card/30 p-3 space-y-3">
            <div className="text-sm font-medium text-foreground">7-Day First Customer Plan</div>
            <ol className="space-y-2 text-xs text-muted-foreground">
              <li>
                <span className="font-medium text-foreground">Day 1:</span> Pick one ICP and send 20 messages.
              </li>
              <li>
                <span className="font-medium text-foreground">Day 2:</span> Send 20 more messages and follow up with Day 1 prospects.
              </li>
              <li>
                <span className="font-medium text-foreground">Day 3:</span> Review replies, refine message, send 25 messages.
              </li>
              <li>
                <span className="font-medium text-foreground">Day 4:</span> Double down on best niche, send 25 messages, book calls.
              </li>
              <li>
                <span className="font-medium text-foreground">Day 5:</span> Offer live demo: "I can generate 5 leads for you right now."
              </li>
              <li>
                <span className="font-medium text-foreground">Day 6:</span> Follow up all interested prospects and push checkout/demo.
              </li>
              <li>
                <span className="font-medium text-foreground">Day 7:</span> Review messages sent, replies, calls booked, paid users; then pick the winning niche for next week.
              </li>
            </ol>
          </div>
        </div>

        <div className="rounded border border-cyan-500/20 bg-card/30 p-3 space-y-3">
          <div className="text-sm font-medium text-foreground">Outbound copy bank</div>
          {activeLead ? (
            <div className="grid grid-cols-1 xl:grid-cols-2 gap-3">
              <div className="rounded border border-cyan-500/10 bg-background/40 p-3 space-y-2">
                <div className="text-xs uppercase tracking-wide text-muted-foreground">Initial</div>
                <pre className="text-xs whitespace-pre-wrap text-muted-foreground">
                  {`Hey - noticed ${activeLead.companyName} is ${activeLead.primaryTrigger}.\n\nTeams at this stage usually need more qualified pipeline without more manual research.\n\nI built LeadIntel to find high-intent leads and write outreach daily.\n\nWant me to generate 5 leads for you?`}
                </pre>
                <Button size="sm" variant="outline" onClick={() => void copyTemplateMessage('initial')}>
                  Copy initial
                </Button>
              </div>
              <div className="rounded border border-cyan-500/10 bg-background/40 p-3 space-y-2">
                <div className="text-xs uppercase tracking-wide text-muted-foreground">Follow-up #1</div>
                <pre className="text-xs whitespace-pre-wrap text-muted-foreground">
                  {`Quick follow-up - I can show you a short lead list for ${activeLead.companyName} so you can judge if it's useful.`}
                </pre>
                <Button size="sm" variant="outline" onClick={() => void copyTemplateMessage('followup1')}>
                  Copy follow-up #1
                </Button>
              </div>
              <div className="rounded border border-cyan-500/10 bg-background/40 p-3 space-y-2">
                <div className="text-xs uppercase tracking-wide text-muted-foreground">Follow-up #2</div>
                <pre className="text-xs whitespace-pre-wrap text-muted-foreground">
                  {'Should I close this out, or would seeing 5 fresh leads for your market be useful?'}
                </pre>
                <Button size="sm" variant="outline" onClick={() => void copyTemplateMessage('followup2')}>
                  Copy follow-up #2
                </Button>
              </div>
              <div className="rounded border border-cyan-500/10 bg-background/40 p-3 space-y-2">
                <div className="text-xs uppercase tracking-wide text-muted-foreground">Booked/demo CTA</div>
                <pre className="text-xs whitespace-pre-wrap text-muted-foreground">
                  {'I can walk you through your lead list live and show how the outreach is generated.'}
                </pre>
              </div>
            </div>
          ) : (
            <div className="text-xs text-muted-foreground">Select a lead to load company-specific copy blocks.</div>
          )}
        </div>
      </CardContent>
    </Card>
  )
}
