import { ImageResponse } from 'next/og'

export const runtime = 'edge'

const FALLBACK_OG_PNG_BASE64 =
  // 1200x630 solid #050a14 PNG (small + deterministic). Used only if ImageResponse fails.
  'iVBORw0KGgoAAAANSUhEUgAABLAAAAJ2CAYAAABPQHtcAAAPTklEQVR42u3YoQ0AAAjAMAwGzf+vwhuEVPSByUVWDwAAAABcFSIAAAAAYGABAAAAgIEFAAAAgIEFAAAAAAYWAAAAABhYAAAAABhYAAAAAGBgAQAAAGBgAQAAAICBBQAAAAAGFgAAAAAGFgAAAAAYWAAAAAAYWAAAAABgYAEAAACAgQUAAACAgQUAAAAABhYAAAAABhYAAAAAGFgAAAAAYGABAAAAYGABAAAAgIEFAAAAgIEFAAAAAAYWAAAAABhYAAAAABhYAAAAAGBgAQAAAGBgAQAAAICBBQAAAAAGFgAAAAAGFgAAAAAYWAAAAAAYWCIAAAAAYGABAAAAgIEFAAAAgIEFAAAAAAYWAAAAABhYAAAAABhYAAAAAGBgAQAAAGBgAQAAAICBBQAAAAAGFgAAAAAGFgAAAAAYWAAAAAAYWAAAAABgYAEAAACAgQUAAACAgQUAAAAABhYAAAAABhYAAAAAGFgAAAAAYGABAAAAYGABAAAAgIEFAAAAgIElBAAAAAAGFgAAAAAYWAAAAAAYWAAAAABgYAEAAACAgQUAAACAgQUAAAAABhYAAAAABhYAAAAAGFgAAAAAYGABAAAAYGABAAAAgIEFAAAAgIEFAAAAAAYWAAAAABhYAAAAABhYAAAAAGBgAQAAAGBgAQAAAICBBQAAAAAGFgAAAAAGFgAAAAAYWAAAAAAYWAAAAABgYAEAAACAgQUAAACAgQUAAAAABhYAAAAAGFgAAAAAGFgAAAAAYGABAAAAYGABAAAAgIEFAAAAAAYWAAAAAAYWAAAAABhYAAAAABhYAAAAAGBgAQAAAICBBQAAAICBBQAAAAAGFgAAAAAGFgAAAAAYWAAAAABgYAEAAABgYAEAAACAgQUAAACAgQUAAAAABhYAAAAAGFgAAAAAGFgAAAAAYGABAAAAgIEFAAAAgIEFAAAAAAYWAAAAAAYWAAAAABhYAAAAAGBgAQAAAGBgAQAAAICBBQAAAICBBQAAAAAGFgAAAAAYWAAAAAAYWAAAAABgYAEAAABgYAEAAACAgQUAAAAABhYAAAAABhYAAAAAGFgAAAAAGFgAAAAAYGABAAAAgIEFAAAAgIEFAAAAAAYWAAAAABhYAAAAABhYAAAAAGBgAQAAAGBgAQAAAICBBQAAAAAGFgAAAAAGFgAAAAAYWAAAAAAYWAAAAABgYAEAAACAgQUAAACAgQUAAAAABhYAAAAABhYAAAAAGFgAAAAAYGABAAAAYGABAAAAgIEFAAAAgIEFAAAAAAYWAAAAABhYAAAAABhYAAAAAGBgAQAAAICBBQAAAICBBQAAAAAGFgAAAAAGFgAAAAAYWAAAAABgYAEAAABgYAEAAACAgQUAAACAgQUAAAAABhYAAAAAGFgAAAAAGFgAAAAAYGABAAAAYGABAAAAgIEFAAAAAAYWAAAAAAYWAAAAABhYAAAAABhYAAAAAGBgAQAAAICBBQAAAICBBQAAAAAGFgAAAAAYWAAAAAAYWAAAAABgYAEAAABgYAEAAACAgQUAAAAABhYAAAAABhYAAAAAGFgAAAAAGFgAAAAAYGABAAAAgIEFAAAAgIEFAAAAAAYWAAAAAAYWAAAAABhYAAAAAGBgAQAAAGBgAQAAAICBBQAAAICBBQAAAAAGFgAAAAAYWAAAAAAYWAAAAABgYAEAAABgYAEAAACAgQUAAAAABhYAAAAABhYAAAAAGFgAAAAAYGABAAAAYGABAAAAgIEFAAAAgIEFAAAAAAYWAAAAABhYAAAAABhYAAAAAGBgAQAAAGBgAQAAAICBBQAAAAAGFgAAAAAGFgAAAAAYWAAAAAAYWAAAAABgYAEAAACAgQUAAACAgQUAAAAABhYAAAAABhYAAAAAGFgAAAAAYGABAAAAYGABAAAAgIEFAAAAAAYWAAAAAAYWAAAAABhYAAAAABhYAAAAAGBgAQAAAICBBQAAAICBBQAAAAAGFgAAAAAGFgAAAAAYWAAAAABgYAEAAABgYAEAAACAgQUAAACAgQUAAAAABhYAAAAAGFgAAAAAGFgAAAAAYGABAAAAYGCJAAAAAICBBQAAAAAGFgAAAAAGFgAAAAAYWAAAAABgYAEAAABgYAEAAACAgQUAAACAgQUAAAAABhYAAAAAGFgAAAAAGFgAAAAAYGABAAAAYGABAAAAgIEFAAAAAAYWAAAAAAYWAAAAABhYAAAAABhYAAAAAGBgAQAAAICBBQAAAICBBQAAAAAGFgAAAAAGlggAAAAAGFgAAAAAYGABAAAAYGABAAAAgIEFAAAAAAYWAAAAAAYWAAAAABhYAAAAABhYAAAAAGBgAQAAAICBBQAAAICBBQAAAAAGFgAAAAAGFgAAAAAYWAAAAABgYAEAAABgYAEAAACAgQUAAACAgQUAAAAABhYAAAAAGFgAAAAAGFgAAAAAYGABAAAAYGCJAAAAAICBBQAAAAAGFgAAAAAGFgAAAAAYWAAAAABgYAEAAABgYAEAAACAgQUAAACAgQUAAAAABhYAAAAAGFgAAAAAGFgAAAAAYGABAAAAYGABAAAAgIEFAAAAAAYWAAAAAAYWAAAAABhYAAAAABhYAAAAAGBgAQAAAICBBQAAAICBBQAAAAAGFgAAAAAGlhAAAAAAGFgAAAAAYGABAAAAYGABAAAAgIEFAAAAAAYWAAAAAAYWAAAAABhYAAAAABhYAAAAAGBgAQAAAICBBQAAAICBBQAAAAAGFgAAAAAGFgAAAAAYWAAAAABgYAEAAABgYAEAAACAgQUAAACAgQUAAAAABhYAAAAAGFgAAAAAGFgAAAAAYGABAAAAYGABAAAAgIEFAAAAAAYWAAAAAAYWAAAAABhYAAAAAGBgAQAAAGBgAQAAAICBBQAAAICBBQAAAAAGFgAAAAAYWAAAAAAYWAAAAABgYAEAAABgYAEAAACAgQUAAAAABhYAAAAABhYAAAAAGFgAAAAAGFgAAAAAYGABAAAAgIEFAAAAgIEFAAAAAAYWAAAAAAYWAAAAABhYAAAAAGBgAQAAAGBgAQAAAICBBQAAAAAGFgAAAAAGFgAAAAAYWAAAAAAYWAAAAABgYAEAAACAgQUAAACAgQUAAAAABhYAAAAABhYAAAAAGFgAAAAAYGABAAAAYGABAAAAgIEFAAAAgIEFAAAAAAYWAAAAABhYAAAAABhYAAAAAGBgAQAAAGBgAQAAAICBBQAAAAAGFgAAAAAGFgAAAAAYWAAAAABgYAEAAABgYAEAAACAgQUAAACAgQUAAAAABhYAAAAAGFgAAAAAGFgAAAAAYGABAAAAYGABAAAAgIEFAAAAAAYWAAAAAAYWAAAAABhYAAAAABhYAAAAAGBgAQAAAICBBQAAAICBBQAAAAAGFgAAAAAGFgAAAAAYWAAAAABgYAEAAABgYAEAAACAgQUAAAAABhYAAAAABhYAAAAAGFgAAAAAGFgAAAAAYGABAAAAgIEFAAAAgIEFAAAAAAYWAAAAAAYWAAAAABhYAAAAAGBgAQAAAGBgAQAAAICBBQAAAICBBQAAAAAGFgAAAAAYWAAAAAAYWAAAAABgYAEAAABgYAEAAACAgQUAAAAABhYAAAAABhYAAAAAGFgAAAAAYGABAAAAYGABAAAAgIEFAAAAgIEFAAAAAAYWAAAAABhYAAAAABhYAAAAAGBgAQAAAGBgAQAAAICBBQAAAAAGFgAAAAAGFgAAAAAYWAAAAAAYWAAAAABgYAEAAACAgQUAAACAgQUAAAAABhYAAAAABhYAAAAAGFgAAAAAYGABAAAAYGABAAAAgIEFAAAAAAYWAAAAAAYWAAAAABhYAAAAABhYAAAAAGBgAQAAAICBBQAAAICBBQAAAAAGFgAAAAAGFgAAAAAYWAAAAABgYAEAAABgYAEAAACAgQUAAACAgQUAAAAABhYAAAAAGFgAAAAAGFgAAAAAYGABAAAAYGABAAAAgIEFAAAAAAYWAAAAAAYWAAAAABhYAAAAAGBgAQAAAGBgAQAAAICBBQAAAICBBQAAAAAGFgAAAAAYWAAAAAAYWAAAAABgYAEAAABgYAEAAACAgQUAAAAABhYAAAAABhYAAAAAGFgAAAAAGFgAAAAAYGABAAAAgIEFAAAAgIEFAAAAAAYWAAAAAAYWAAAAABhYAAAAAGBgAQAAAGBgAQAAAICBBQAAAICBJQIAAAAABhYAAAAAGFgAAAAAGFgAAAAAYGABAAAAgIEFAAAAgIEFAAAAAAYWAAAAAAYWAAAAABhYAAAAAGBgAQAAAGBgAQAAAICBBQAAAICBBQAAAAAGFgAAAAAYWAAAAAAYWAAAAABgYAEAAABgYAEAAACAgQUAAAAABhYAAAAABhYAAAAAGFgAAAAAGFgiAAAAAGBgAQAAAICBBQAAAICBBQAAAAAGFgAAAAAYWAAAAAAYWAAAAABgYAEAAABgYAEAAACAgQUAAAAABhYAAAAABhYAAAAAGFgAAAAAGFgAAAAAYGABAAAAgIEFAAAAgIEFAAAAAAYWAAAAAAYWAAAAABhYAAAAAGBgAQAAAGBgAQAAAICBBQAAAICBJQIAAAAABhYAAAAAGFgAAAAAGFgAAAAAYGABAAAAgIEFAAAAgIEFAAAAAAYWAAAAAAYWAAAAABhYAAAAAGBgAQAAAGBgAQAAAICBBQAAAICBBQAAAAAGFgAAAAAYWAAAAAAYWAAAAABgYAEAAABgYAEAAACAgQUAAAAABhYAAAAABhYAAAAAGFgAAAAAGFhCAAAAAGBgAQAAAICBBQAAAICBBQAAAAAGFgAAAAAYWAAAAAAYWAAAAABgYAEAAABgYAEAAACAgQUAAAAABhYAAAAABhYAAAAAGFgAAAAAGFgAAAAAYGABAAAAgIEFAAAAgIEFAAAAAAYWAAAAAAYWAAAAABhYAAAAAGBgAQAAAGBgAQAAAICBBQAAAICBBQAAAAAGFgAAAAAYWAAAAAAYWAAAAABgYAEAAACAgQUAAACAgQUAAAAABhYAAAAABhYAAAAAGFgAAAAAYGABAAAAYGABAAAAgIEFAAAAgIEFAAAAAAYWAAAAABhYAAAAABhYAAAAAGBgAQAAAGBgAQAAAICBBQAAAAAGFgAAAAAGFgAAAAAYWAAAAAAYWAAAAABgYAEAAACAgQUAAACAgQUAAAAABhYAAAAABhYAAAAAGFgAAAAAYGABAAAAYGABAAAAgIEFAAAAAAYWAAAAAAYWAAAAABhYAAAAABhYAAAAAGBgAQAAAICBBQAAAICBBQAAAAAGFgAAAAAGFgAAAAAYWAAAAABgYAEAAABgYAEAAACAgQUAAACAgQUAAAAABhYAAAAAGFgAAAAAGFgAAAAAYGABAAAAYGABAAAAgIEFAAAAAAYWAAAAAAYWAAAAABhYAAAAAGBgAQAAAGBgAQAAAICBBQAAAICBBQAAAAAGFgAAAAAYWAAAAAAYWAAAAABgYAEAAABgYAEAAACAgQUAAAAABhYAAAAABhYAAAAAGFgAAAAAGFgAAAAAYGABAAAAgIEFAAAAgIEFAAAAAAYWAAAAAAYWAAAAABhYAAAAAGBgAQAAAGBgAQAAAICBBQAAAAAGFgAAAAAGFgAAAAAYWAAAAAAYWAAAAABgYAEAAACAgQUAAACAgQUAAAAABhYAAAAABhYAAAAAGFgAAAAAYGABAAAAYGABAAAAgIEFAAAAAAYWAAAAAAYWAAAAABhYAAAAABhYAAAAAGBgAQAAAICBBQAAAICBBQAAAAAGFgAAAAAGFgAAAAAYWAAAAABgYAEAAABgYAEAAACAgQUAAACAgQUAAAAABhYAAAAAGFgAAAAAGFgAAAAAYGABAAAAYGABAAAAgIEFAAAAAAYWAAAAAAYWAAAAABhYAAAAAGBgAQAAAGBgAQAAAICBBQAAAICBBQAAAAAGFgAAAAAYWAAAAAAYWAAAAABgYAEAAABgYAEAAACAgQUAAAAABhYAAAAABhYAAAAAGFgAAAAAGFgAAAAAYGABAAAAgIEFAAAAgIEFAAAAAAYWAAAAAAYWAAAAABhYAAAAAGBgAQAAAGBgAQAAAICBBQAAAICBJQIAAAAABhYAAAAAGFgAAAAAGFgAAAAAYGABAAAAgIEFAAAAgIEFAAAAAAYWAAAAAAYWAAAAABhYAAAAAGBgAQAAAGBgAQAAAICBBQAAAICBBQAAAAAGFgAAAAAYWAAAAAAYWAAAAABgYAEAAABgYAEAAACAgQUAAAAABhYAAAAABhYAAAAAGFgAAAAAGFgiAAAAAGBgAQAAAICBBQAAAICBBQAAAAAGFgAAAAAYWAAAAAAYWAAAAABgYAEAAABgYAEAAACAgQUAAAAABhYAAAAABhYAAAAAGFgAAAAAGFgAAAAAYGABAAAAgIEFAAAAgIEFAAAAAAYWAAAAAAYWAAAAABhYAAAAAGBgAQAAAGBgAQAAAICBBQAAAICBBQAAAAAGFgAAAAAYWAAAAAAYWAAAAABgYAEAAACAgQUAAACAgQUAAAAABhYAAAAABhYAAAAAGFgAAAAAYGABAAAAYGABAAAAgIEFAAAAgIEFAAAAAAYWAAAAABhYAAAAABhYAAAAAGBgAQAAAGBgAQAAAICBBQAAAAAGFgAAAAAfLJ3tGk9nW47HAAAAAElFTkSuQmCC'

function base64ToUint8Array(b64: string): Uint8Array {
  const bin = atob(b64)
  const out = new Uint8Array(bin.length)
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i)
  return out
}

function fallbackOgPng(): Response {
  const bytes = base64ToUint8Array(FALLBACK_OG_PNG_BASE64)
  // Wrap in a Blob so TS consistently accepts it as BodyInit across DOM lib variants.
  // Ensure the BlobPart is a real ArrayBuffer (not ArrayBufferLike), to satisfy stricter lib.dom typings.
  const ab = bytes.buffer instanceof ArrayBuffer ? bytes.buffer : new Uint8Array(bytes).buffer
  return new Response(new Blob([ab], { type: 'image/png' }), {
    headers: {
      'Content-Type': 'image/png',
      'Cache-Control': 'public, max-age=0, must-revalidate',
      'X-OG-Mode': 'fallback',
    },
  })
}

export async function GET(request: Request) {
  try {
    const { searchParams } = new URL(request.url)
    const title = (searchParams.get('title') || 'LeadIntel').trim().slice(0, 80)
    const subtitle = (searchParams.get('subtitle') || 'Trigger-based alerts → instant pitches').trim().slice(0, 120)
    const host = (() => {
      try {
        return new URL(request.url).hostname
      } catch {
        return 'raelinfo.com'
      }
    })()

    const res = new ImageResponse(
      (
        <div
          style={{
            width: '1200px',
            height: '630px',
            display: 'flex',
            flexDirection: 'column',
            position: 'relative',
            backgroundColor: '#050a14',
            color: '#e5e7eb',
            padding: '56px',
            fontFamily:
              'ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial, "Apple Color Emoji", "Segoe UI Emoji"',
          }}
        >
          <div
            style={{
              position: 'absolute',
              inset: 0,
              backgroundImage:
                'linear-gradient(rgba(34,211,238,0.10) 1px, transparent 1px), linear-gradient(90deg, rgba(34,211,238,0.10) 1px, transparent 1px)',
              backgroundSize: '48px 48px',
              opacity: 0.25,
            }}
          />

          <div style={{ position: 'relative', display: 'flex', flexDirection: 'column', gap: 22, width: '100%' }}>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
              <div style={{ fontSize: 28, fontWeight: 700, color: '#22d3ee', letterSpacing: 0.2 }}>LeadIntel</div>
              <div
                style={{
                  fontSize: 14,
                  color: '#94a3b8',
                  border: '1px solid rgba(34,211,238,0.25)',
                  padding: '8px 12px',
                  borderRadius: 999,
                }}
              >
                {host}
              </div>
            </div>

            <div
              style={{
                border: '1px solid rgba(34,211,238,0.25)',
                borderRadius: 20,
                background: 'rgba(2,6,23,0.75)',
                display: 'flex',
                flexDirection: 'column',
                padding: 34,
                boxShadow: '0 0 60px rgba(34,211,238,0.08)',
              }}
            >
              <div style={{ fontSize: 14, color: '#94a3b8', marginBottom: 14, letterSpacing: 1.2 }}>
                TERMINAL BRIEF
              </div>
              <div style={{ fontSize: 58, fontWeight: 800, lineHeight: 1.05 }}>{title}</div>
              <div style={{ marginTop: 18, fontSize: 22, color: '#cbd5e1', lineHeight: 1.35 }}>{subtitle}</div>
            </div>

            <div style={{ display: 'flex', gap: 12, marginTop: 6 }}>
              <div
                style={{
                  border: '1px solid rgba(168,85,247,0.30)',
                  background: 'rgba(168,85,247,0.10)',
                  color: '#e9d5ff',
                  padding: '10px 14px',
                  borderRadius: 999,
                  fontSize: 16,
                  fontWeight: 600,
                }}
              >
                Trigger signals
              </div>
              <div
                style={{
                  border: '1px solid rgba(34,211,238,0.30)',
                  background: 'rgba(34,211,238,0.10)',
                  color: '#a5f3fc',
                  padding: '10px 14px',
                  borderRadius: 999,
                  fontSize: 16,
                  fontWeight: 600,
                }}
              >
                0–100 score
              </div>
              <div
                style={{
                  border: '1px solid rgba(16,185,129,0.30)',
                  background: 'rgba(16,185,129,0.10)',
                  color: '#bbf7d0',
                  padding: '10px 14px',
                  borderRadius: 999,
                  fontSize: 16,
                  fontWeight: 600,
                }}
              >
                Send-ready outreach
              </div>
            </div>
          </div>
        </div>
      ),
      {
        width: 1200,
        height: 630,
        headers: {
          // Don't cache forever: a broken render should not get stuck as an immutable 0-byte image.
          'Cache-Control': 'public, max-age=0, must-revalidate',
          'X-OG-Mode': 'dynamic',
        },
      }
    )

    return res
  } catch {
    return fallbackOgPng()
  }
}

