begin;

create table if not exists api.digest_lite_subscribers (
  id bigint generated by default as identity primary key,
  email text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists digest_lite_subscribers_email_unique
  on api.digest_lite_subscribers (lower(email));

alter table api.digest_lite_subscribers enable row level security;

commit;

