begin;

create extension if not exists pgcrypto;
set local search_path = public, extensions, api;

-- Lead capture (public acquisition, privacy-safe).
-- Notes:
-- - Stored in `api` schema for consistency.
-- - RLS: allow inserts from anon/auth; reads restricted by default.
-- - Avoid storing sensitive info; keep message short and optional.
create table if not exists api.lead_captures (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  user_id uuid null references auth.users(id) on delete set null,
  email text not null,
  company text null,
  role text null,
  intent text not null check (intent in ('demo','pricing_question','trial_help','general')),
  message text null,
  route text not null,
  referrer text null,
  utm_source text null,
  utm_medium text null,
  utm_campaign text null,
  device_class text not null check (device_class in ('mobile','desktop','unknown')),
  viewport_w int null,
  viewport_h int null,
  -- Idempotency/dedupe: prevent repeated spammy submits for same email+intent+route in a short window.
  -- Generated by server route; opaque hash string (no secrets).
  dedupe_key text not null,
  meta jsonb not null default '{}'::jsonb
);

alter table api.lead_captures enable row level security;

create index if not exists lead_captures_created_at_idx on api.lead_captures (created_at desc);
create index if not exists lead_captures_email_idx on api.lead_captures (email);
create index if not exists lead_captures_intent_idx on api.lead_captures (intent);
create unique index if not exists lead_captures_dedupe_key_uq on api.lead_captures (dedupe_key);

drop policy if exists lead_captures_insert on api.lead_captures;
create policy lead_captures_insert
on api.lead_captures
for insert
with check (
  (user_id is null) or (auth.uid() is not null and user_id = auth.uid())
);

-- Reads are intentionally restricted (no select policy).

notify pgrst, 'reload schema';
commit;

