import { TEMPLATE_TOKEN_GLOSSARY, type TemplateTokenDef } from '@/lib/templates/tokens'

export type { TemplateTokenDef } from '@/lib/templates/tokens'

export type TemplateChannel = 'email' | 'linkedin' | 'call'

export type TemplateTrigger =
  | 'funding'
  | 'hiring_spike'
  | 'partnership'
  | 'product_launch'
  | 'competitive_displacement'
  | 'expansion'

export type TemplateLength = 'short' | 'medium' | 'breakup' | 'followup' | 'ultra_short' | 'value' | 'opener'

export type OutreachTemplate = {
  id: string
  slug: string
  trigger: TemplateTrigger
  channel: TemplateChannel
  persona: 'sdr_ae'
  length: TemplateLength
  title: string
  tags: string[]
  tokens: string[]
  related_use_case_path: string
  subject: string | null
  body: string
  notes: string
}

function listTokens(args: { subject: string | null; body: string }): string[] {
  const set = new Set<string>()
  const re = /\{\{[a-z0-9_]+\}\}/gi
  const joined = `${args.subject ?? ''}\n${args.body}`
  for (const m of joined.matchAll(re)) {
    set.add(m[0].toLowerCase())
  }
  return Array.from(set).sort((a, b) => a.localeCompare(b))
}

function t(template: Omit<OutreachTemplate, 'tokens'>): OutreachTemplate {
  return { ...template, tokens: listTokens({ subject: template.subject, body: template.body }) }
}

export const TEMPLATE_TOKENS: TemplateTokenDef[] = TEMPLATE_TOKEN_GLOSSARY

export const TEMPLATE_LIBRARY: OutreachTemplate[] = [
  // Funding (10)
  t({
    id: 'funding-email-1-short',
    slug: 'funding-email-1-short',
    trigger: 'funding',
    channel: 'email',
    persona: 'sdr_ae',
    length: 'short',
    title: 'Funding — email #1 (short)',
    tags: ['funding', 'email', 'cold', 'why_now'],
    related_use_case_path: '/use-cases/funding-outreach',
    subject: 'Quick question after {{trigger_event}}',
    notes: 'Best when a funding signal just hit and teams are re-prioritizing initiatives and owners.',
    body:
      'Hi {{name}} — congrats on {{trigger_event}} at {{company}}.\n\nWhen funding lands, teams usually pick 1–2 priorities quickly (pipeline coverage, enablement, reporting, consolidation). The timing window is early—before a shortlist forms and internal owners lock the plan.\n\nIf {{initiative}} is one of the priorities in the next {{timeframe}}, I can share a one-page checklist we use to turn “why now” signals into a daily shortlist and a send-ready draft reps can ship without a blank page.\n\nWorth a 12-minute call to see it, or should I ask {{alt_owner}}?',
  }),
  t({
    id: 'funding-email-2-medium',
    slug: 'funding-email-2-medium',
    trigger: 'funding',
    channel: 'email',
    persona: 'sdr_ae',
    length: 'medium',
    title: 'Funding — email #2 (medium)',
    tags: ['funding', 'email', 'cold', 'prioritization'],
    related_use_case_path: '/use-cases/funding-outreach',
    subject: 'A simple way to turn {{trigger_event}} into weekly execution',
    notes: 'Use when you want to lead with a concrete execution system (signals → shortlist → draft) rather than product features.',
    body:
      'Hi {{name}} — congrats again on {{trigger_event}}.\n\nIn the first few weeks after funding, outbound often gets messy in two places:\n- prioritization (who is “worth touching today”)\n- consistency (reps writing different versions of the same message)\n\nIf {{initiative}} is on the roadmap for {{company}} this quarter, here’s the workflow we recommend:\n1) track a watchlist of target accounts\n2) alert on “why now” triggers tied to that list\n3) generate a daily shortlist with a deterministic 0–100 score\n4) draft outreach (email/DM/call opener) with tokens like {{company}}, {{trigger_event}}, and {{initiative}}\n\nIf you tell me which team owns {{metric}} for outbound, I’ll tailor the checklist to your motion.\n\nOpen to a quick 15-minute walkthrough next week?',
  }),
  t({
    id: 'funding-email-3-breakup',
    slug: 'funding-email-3-breakup',
    trigger: 'funding',
    channel: 'email',
    persona: 'sdr_ae',
    length: 'breakup',
    title: 'Funding — email #3 (breakup)',
    tags: ['funding', 'email', 'breakup', 'permission'],
    related_use_case_path: '/use-cases/funding-outreach',
    subject: 'Should I close this out for {{company}}?',
    notes: 'Use as a clean close-the-loop when there is no response; avoids guilt and keeps timing control with the buyer.',
    body:
      'Hi {{name}} — quick close-the-loop.\n\nI reached out because {{trigger_event}} usually creates a short window where {{initiative}} gets set, the owner is clear, and teams decide what “good” looks like for the next {{timeframe}}.\n\nThe pattern we see post-funding is consistent:\n- a small set of priorities gets picked fast\n- teams scramble to decide who to focus on first\n- reps end up writing five versions of the same “why now” message\n\nIf that’s not a priority at {{company}} right now, no problem — I can close this out and circle back later when timing changes.\n\nIf it is a priority, what’s the right next step: should I send the one-page checklist, or are you open to a quick 12-minute call with whoever owns {{metric}}?',
  }),
  t({
    id: 'funding-email-followup-1',
    slug: 'funding-email-followup-1',
    trigger: 'funding',
    channel: 'email',
    persona: 'sdr_ae',
    length: 'followup',
    title: 'Funding — email follow-up #1 (value, no guilt)',
    tags: ['funding', 'email', 'followup', 'value'],
    related_use_case_path: '/use-cases/funding-outreach',
    subject: 'One-page checklist for {{initiative}} after {{trigger_event}}',
    notes: 'Send 2 days after first email; offers a concrete artifact and one easy question.',
    body:
      'Hi {{name}} — following up with something tangible.\n\nAfter {{trigger_event}}, teams often ask two questions at the same time:\n1) “who do we focus on first?”\n2) “how do we keep messaging consistent while we move fast?”\n\nI can send a one-page checklist for {{initiative}} that covers:\n- which signals to watch on your target list (so timing is real)\n- how to score and prioritize daily (so reps aren’t guessing)\n- how to draft a first-touch message that’s specific without inventing facts\n\nIt also includes a simple handoff: if a rep can’t fill {{initiative}} or {{metric}} with real context, the play changes (so you don’t ship generic spam).\n\nIf you want it, reply “checklist” and I’ll send it over.\n\nIf you’d rather talk it through, are you open to a quick 12-minute call this week?',
  }),
  t({
    id: 'funding-email-followup-2',
    slug: 'funding-email-followup-2',
    trigger: 'funding',
    channel: 'email',
    persona: 'sdr_ae',
    length: 'followup',
    title: 'Funding — email follow-up #2 (tight ask)',
    tags: ['funding', 'email', 'followup', 'owner'],
    related_use_case_path: '/use-cases/funding-outreach',
    subject: 'Who owns {{initiative}} execution at {{company}}?',
    notes: 'Send 5 days after first email; tight owner/timing question with a clear next step.',
    body:
      'Hi {{name}} — quick question so I don’t spam the wrong person.\n\nFor {{company}}, who owns execution for {{initiative}} after {{trigger_event}} — you or {{alt_owner}}?\n\nIf it’s you, I can send:\n- a short “signals → shortlist → draft” workflow\n- a one-page checklist your team can reuse\n- a few copy examples tied to {{metric}} (so it’s measurable)\n\nIf it’s {{alt_owner}}, I’m happy to reach out directly and keep you out of the thread.\n\nWhich way should I go — and if it’s you, are you open to a quick 12-minute call to align on {{initiative}} timing?',
  }),
  t({
    id: 'funding-linkedin-1-ultra-short',
    slug: 'funding-linkedin-1-ultra-short',
    trigger: 'funding',
    channel: 'linkedin',
    persona: 'sdr_ae',
    length: 'ultra_short',
    title: 'Funding — LinkedIn DM #1 (ultra short)',
    tags: ['funding', 'linkedin', 'dm', 'ultra_short'],
    related_use_case_path: '/use-cases/funding-outreach',
    subject: null,
    notes: 'Use right after a funding announcement. Keep it to one question.',
    body:
      'Congrats on {{trigger_event}} at {{company}} — are you prioritizing {{initiative}} in the next {{timeframe}}, or is it {{alt_initiative}}?',
  }),
  t({
    id: 'funding-linkedin-2-value',
    slug: 'funding-linkedin-2-value',
    trigger: 'funding',
    channel: 'linkedin',
    persona: 'sdr_ae',
    length: 'value',
    title: 'Funding — LinkedIn DM #2 (value + question)',
    tags: ['funding', 'linkedin', 'dm', 'value'],
    related_use_case_path: '/use-cases/funding-outreach',
    subject: null,
    notes: 'Use when you want to offer a concrete artifact (checklist) and ask permission.',
    body:
      'After {{trigger_event}}, teams usually pick priorities fast and outbound gets noisy.\n\nIf {{initiative}} matters for {{company}} this quarter, I can share a one-page checklist to turn “why now” signals into a daily shortlist + a send-ready draft.\n\nWant it?',
  }),
  t({
    id: 'funding-linkedin-followup',
    slug: 'funding-linkedin-followup',
    trigger: 'funding',
    channel: 'linkedin',
    persona: 'sdr_ae',
    length: 'followup',
    title: 'Funding — LinkedIn DM follow-up',
    tags: ['funding', 'linkedin', 'dm', 'followup'],
    related_use_case_path: '/use-cases/funding-outreach',
    subject: null,
    notes: 'Use as a short nudge: owner + timeline question.',
    body:
      'Quick follow-up: who owns {{initiative}} execution at {{company}} after {{trigger_event}}—you or {{alt_owner}}?\n\nIf you point me to the owner, I’ll send the checklist and examples tied to {{metric}}.',
  }),
  t({
    id: 'funding-call-1-opener',
    slug: 'funding-call-1-opener',
    trigger: 'funding',
    channel: 'call',
    persona: 'sdr_ae',
    length: 'opener',
    title: 'Funding — call opener #1',
    tags: ['funding', 'call', 'opener'],
    related_use_case_path: '/use-cases/funding-outreach',
    subject: null,
    notes: 'Use when you want to qualify priority + owner quickly.',
    body:
      'Hey {{name}} — congrats on {{trigger_event}} at {{company}}. I’m calling because right after funding, teams usually pick a priority like {{initiative}} and the owner changes fast. Quick question: is {{initiative}} a focus in the next {{timeframe}}, or is it something else?',
  }),
  t({
    id: 'funding-call-2-opener',
    slug: 'funding-call-2-opener',
    trigger: 'funding',
    channel: 'call',
    persona: 'sdr_ae',
    length: 'opener',
    title: 'Funding — call opener #2',
    tags: ['funding', 'call', 'opener', 'owner'],
    related_use_case_path: '/use-cases/funding-outreach',
    subject: null,
    notes: 'Use when you want to route to the right person without pitching.',
    body:
      'Hi {{name}} — quick routing question. After {{trigger_event}}, who owns outbound execution for {{initiative}} at {{company}}—you or {{alt_owner}}? I can send a one-page checklist and a few copy examples tied to {{metric}}.',
  }),

  // Hiring spike (10)
  t({
    id: 'hiring-spike-email-1-short',
    slug: 'hiring-spike-email-1-short',
    trigger: 'hiring_spike',
    channel: 'email',
    persona: 'sdr_ae',
    length: 'short',
    title: 'Hiring spike — email #1 (short)',
    tags: ['hiring_spike', 'email', 'cold', 'why_now'],
    related_use_case_path: '/use-cases/hiring-spike',
    subject: 'Quick question on the hiring push at {{company}}',
    notes: 'Best when hiring signals suggest a build phase and process/tool decisions are being made.',
    body:
      'Hi {{name}} — I noticed a hiring push in {{function}} at {{company}} (especially roles like {{role}}).\n\nWhen teams hire fast, the first thing that breaks is consistency: different reps say different things, and “who should we contact today?” becomes a guess.\n\nIf the hiring is tied to {{initiative}} in the next {{timeframe}}, I can share a simple workflow: timing signals → daily shortlist → drafts with tokens ({{company}}, {{role}}, {{initiative}}) so new reps can ramp without inventing context.\n\nWorth a 12-minute call, or should I ask {{alt_owner}}?',
  }),
  t({
    id: 'hiring-spike-email-2-medium',
    slug: 'hiring-spike-email-2-medium',
    trigger: 'hiring_spike',
    channel: 'email',
    persona: 'sdr_ae',
    length: 'medium',
    title: 'Hiring spike — email #2 (medium)',
    tags: ['hiring_spike', 'email', 'cold', 'enablement'],
    related_use_case_path: '/use-cases/hiring-spike',
    subject: 'How teams keep messaging consistent during a hiring spike',
    notes: 'Use when you want to lead with enablement + prioritization outcomes.',
    body:
      'Hi {{name}} — the hiring spike at {{company}} caught my eye.\n\nWhen headcount grows in {{function}}, teams usually face the same pattern:\n- leadership wants speed (more touches, more meetings)\n- reps want clarity (who to contact, what to say)\n- ops wants consistency (templates that don’t drift)\n\nIf you’re trying to improve {{metric}} while ramping new reps into {{initiative}}, the tightest loop is:\n1) keep a watchlist of target accounts\n2) alert on timing signals\n3) score/prioritize daily with visible reasons\n4) generate drafts with standardized tokens so copy stays on-message\n\nOpen to a quick 15-minute walkthrough to see examples and decide if it fits your workflow?',
  }),
  t({
    id: 'hiring-spike-email-3-breakup',
    slug: 'hiring-spike-email-3-breakup',
    trigger: 'hiring_spike',
    channel: 'email',
    persona: 'sdr_ae',
    length: 'breakup',
    title: 'Hiring spike — email #3 (breakup)',
    tags: ['hiring_spike', 'email', 'breakup', 'permission'],
    related_use_case_path: '/use-cases/hiring-spike',
    subject: 'Should I close this out for {{company}}?',
    notes: 'Use when you need a respectful close; keeps timing control with the buyer.',
    body:
      'Hi {{name}} — quick close-the-loop.\n\nI reached out because hiring spikes in {{function}} often mean a build phase, and teams decide quickly how they’ll run {{initiative}} without letting messaging drift.\n\nThe reason I’m persistent is simple: once new reps ramp, the workflow tends to “lock in” (who to prioritize, what counts as a strong signal, and what copy is considered on-message).\n\nIf that’s not a priority for {{company}} in the next {{timeframe}}, no problem — I can close this out and circle back later.\n\nIf it is a priority, what’s the right next step: should I send the one-page ramp checklist, or are you open to a quick 12-minute call with whoever owns {{metric}}?',
  }),
  t({
    id: 'hiring-spike-email-followup-1',
    slug: 'hiring-spike-email-followup-1',
    trigger: 'hiring_spike',
    channel: 'email',
    persona: 'sdr_ae',
    length: 'followup',
    title: 'Hiring spike — email follow-up #1 (value, no guilt)',
    tags: ['hiring_spike', 'email', 'followup', 'value'],
    related_use_case_path: '/use-cases/hiring-spike',
    subject: 'One-page ramp checklist for new reps ({{function}})',
    notes: 'Send Day 2; delivers value and asks one question.',
    body:
      'Hi {{name}} — sharing a small artifact in case it helps.\n\nWhen teams add roles like {{role}} during a hiring push, the fastest way to keep output consistent is to standardize two things:\n- what signals count as “why now” (so reps aren’t guessing)\n- what a first-touch message looks like for {{initiative}} (so copy doesn’t drift)\n\nI can send a one-page ramp checklist for {{company}} that includes:\n- a simple signal rubric tied to {{metric}}\n- a daily prioritization routine (watchlist → shortlist)\n- a tokenized draft your team can reuse without inventing context\n\nIf you want it, I can send it here — or if you’re open to a quick 12-minute call, I’ll tailor it to how {{function}} is ramping at {{company}}. Which is easier?',
  }),
  t({
    id: 'hiring-spike-email-followup-2',
    slug: 'hiring-spike-email-followup-2',
    trigger: 'hiring_spike',
    channel: 'email',
    persona: 'sdr_ae',
    length: 'followup',
    title: 'Hiring spike — email follow-up #2 (tight ask)',
    tags: ['hiring_spike', 'email', 'followup', 'owner'],
    related_use_case_path: '/use-cases/hiring-spike',
    subject: 'Who owns {{initiative}} execution at {{company}}?',
    notes: 'Send Day 5; tight owner question, then stop.',
    body:
      'Hi {{name}} — last quick one.\n\nFor {{company}}, who owns the workflow for {{initiative}} during this hiring push — your team, or {{alt_owner}}?\n\nIf you point me to the owner, I’ll send:\n- the one-page checklist\n- a few copy examples aligned to {{metric}}\n- the “stop rules” (when not to send because context is missing)\n\nIf it’s you, are you open to a quick 12-minute call to confirm how you’re measuring {{initiative}} impact over the next {{timeframe}}?',
  }),
  t({
    id: 'hiring-spike-linkedin-1-ultra-short',
    slug: 'hiring-spike-linkedin-1-ultra-short',
    trigger: 'hiring_spike',
    channel: 'linkedin',
    persona: 'sdr_ae',
    length: 'ultra_short',
    title: 'Hiring spike — LinkedIn DM #1 (ultra short)',
    tags: ['hiring_spike', 'linkedin', 'dm', 'ultra_short'],
    related_use_case_path: '/use-cases/hiring-spike',
    subject: null,
    notes: 'Use when the hiring signal is fresh; one question only.',
    body:
      'Saw the hiring push in {{function}} at {{company}} — is it tied to {{initiative}} in the next {{timeframe}}, or something else?',
  }),
  t({
    id: 'hiring-spike-linkedin-2-value',
    slug: 'hiring-spike-linkedin-2-value',
    trigger: 'hiring_spike',
    channel: 'linkedin',
    persona: 'sdr_ae',
    length: 'value',
    title: 'Hiring spike — LinkedIn DM #2 (value + question)',
    tags: ['hiring_spike', 'linkedin', 'dm', 'value'],
    related_use_case_path: '/use-cases/hiring-spike',
    subject: null,
    notes: 'Use when you want to offer a checklist (not a pitch).',
    body:
      'Hiring spikes usually mean a build phase—and messaging tends to drift.\n\nIf {{company}} is hiring in {{function}} because of {{initiative}}, I can share a one-page checklist: signals to watch + a tokenized draft + a daily shortlist routine tied to {{metric}}.\n\nWant it?',
  }),
  t({
    id: 'hiring-spike-linkedin-followup',
    slug: 'hiring-spike-linkedin-followup',
    trigger: 'hiring_spike',
    channel: 'linkedin',
    persona: 'sdr_ae',
    length: 'followup',
    title: 'Hiring spike — LinkedIn DM follow-up',
    tags: ['hiring_spike', 'linkedin', 'dm', 'followup'],
    related_use_case_path: '/use-cases/hiring-spike',
    subject: null,
    notes: 'Use as an owner-routing follow-up.',
    body:
      'Quick follow-up: who owns {{initiative}} execution at {{company}} during this hiring push—your team or {{alt_owner}}?\n\nIf you point me to the owner, I’ll send the checklist and examples tied to {{metric}}.',
  }),
  t({
    id: 'hiring-spike-call-1-opener',
    slug: 'hiring-spike-call-1-opener',
    trigger: 'hiring_spike',
    channel: 'call',
    persona: 'sdr_ae',
    length: 'opener',
    title: 'Hiring spike — call opener #1',
    tags: ['hiring_spike', 'call', 'opener'],
    related_use_case_path: '/use-cases/hiring-spike',
    subject: null,
    notes: 'Qualify the initiative + timeline in one question.',
    body:
      'Hey {{name}} — I’m calling because I saw the hiring push in {{function}} at {{company}} (roles like {{role}}). Quick question: is the hiring tied to {{initiative}} in the next {{timeframe}}, or is it a different priority?',
  }),
  t({
    id: 'hiring-spike-call-2-opener',
    slug: 'hiring-spike-call-2-opener',
    trigger: 'hiring_spike',
    channel: 'call',
    persona: 'sdr_ae',
    length: 'opener',
    title: 'Hiring spike — call opener #2',
    tags: ['hiring_spike', 'call', 'opener', 'owner'],
    related_use_case_path: '/use-cases/hiring-spike',
    subject: null,
    notes: 'Owner routing without pitching.',
    body:
      'Hi {{name}} — quick routing question. During this hiring push, who owns enablement and the outbound workflow for {{initiative}} at {{company}}—you or {{alt_owner}}? I can send a one-page checklist tied to {{metric}}.',
  }),

  // Partnership (10)
  t({
    id: 'partnership-email-1-short',
    slug: 'partnership-email-1-short',
    trigger: 'partnership',
    channel: 'email',
    persona: 'sdr_ae',
    length: 'short',
    title: 'Partnership — email #1 (short)',
    tags: ['partnership', 'email', 'cold', 'rollout'],
    related_use_case_path: '/use-cases/partnership-announcement',
    subject: 'Quick question on the {{partner}} rollout',
    notes: 'Best when a partnership announcement implies new handoffs, routing, or enablement changes.',
    body:
      'Hi {{name}} — congrats on the {{partner}} announcement.\n\nPartnership rollouts usually get stuck in one place: handoffs. The work is less about the press release and more about “who owns what,” “what gets reported,” and “how reps message it.”\n\nIf the rollout touches {{handoff}} between {{system_a}} and {{system_b}} for {{company}}, I can share a short rollout checklist and a tokenized draft that ties the rollout to a clear “why now” next step.\n\nWorth a 12-minute call to compare notes, or should I ask {{alt_owner}}?',
  }),
  t({
    id: 'partnership-email-2-medium',
    slug: 'partnership-email-2-medium',
    trigger: 'partnership',
    channel: 'email',
    persona: 'sdr_ae',
    length: 'medium',
    title: 'Partnership — email #2 (medium)',
    tags: ['partnership', 'email', 'cold', 'enablement'],
    related_use_case_path: '/use-cases/partnership-announcement',
    subject: 'Pilot → GA: avoiding rollout friction',
    notes: 'Use when you want to frame rollout as ownership/reporting/enablement—not features.',
    body:
      'Hi {{name}} — quick note on partnership rollouts.\n\nWhether you’re in {{stage}} or moving from pilot to GA, friction tends to show up in three places:\n1) ownership: who handles {{handoff}} and who gets alerted\n2) reporting: what counts as success for {{metric}}\n3) enablement: how reps explain “why now” without inventing context\n\nIf {{company}} is rolling out with {{partner}}, I can send a short checklist + example copy that uses tokens like {{company}}, {{partner}}, {{handoff}}, and {{trigger_event}} so the message stays consistent across the team.\n\nOpen to a quick 15-minute walkthrough this week?',
  }),
  t({
    id: 'partnership-email-3-breakup',
    slug: 'partnership-email-3-breakup',
    trigger: 'partnership',
    channel: 'email',
    persona: 'sdr_ae',
    length: 'breakup',
    title: 'Partnership — email #3 (breakup)',
    tags: ['partnership', 'email', 'breakup', 'permission'],
    related_use_case_path: '/use-cases/partnership-announcement',
    subject: 'Close the loop on {{partner}} rollout?',
    notes: 'Use when you want a clean close without guilt.',
    body:
      'Hi {{name}} — quick close-the-loop.\n\nI reached out because partnership rollouts often create a narrow window to standardize messaging and ownership around {{handoff}}.\n\nIf that’s not a focus for {{company}} right now, no problem — I can close this out and circle back when timing changes.\n\nIf it is a focus, I can share a short checklist (ownership map + enablement + reporting) and a couple of copy examples that reference {{partner}} without over-claiming.\n\nWould you prefer I send that, or are you open to a quick 12-minute call with the owner for {{metric}} to align on rollout timing?',
  }),
  t({
    id: 'partnership-email-followup-1',
    slug: 'partnership-email-followup-1',
    trigger: 'partnership',
    channel: 'email',
    persona: 'sdr_ae',
    length: 'followup',
    title: 'Partnership — email follow-up #1 (value)',
    tags: ['partnership', 'email', 'followup', 'value'],
    related_use_case_path: '/use-cases/partnership-announcement',
    subject: 'Checklist for handoffs + enablement during rollout',
    notes: 'Day 2 follow-up; offers an artifact and asks permission.',
    body:
      'Hi {{name}} — following up with something concrete.\n\nI put together a short checklist for partnership rollouts that covers:\n- mapping ownership for {{handoff}}\n- defining one metric for success ({{metric}})\n- drafting outreach that references {{partner}} without over-claiming\n- “stop rules” so reps don’t message without real context\n\nIf it’s useful for {{company}}, reply “checklist” and I’ll send it.\n\nIf you’d rather talk, are you open to a quick 12-minute call this week?',
  }),
  t({
    id: 'partnership-email-followup-2',
    slug: 'partnership-email-followup-2',
    trigger: 'partnership',
    channel: 'email',
    persona: 'sdr_ae',
    length: 'followup',
    title: 'Partnership — email follow-up #2 (tight ask)',
    tags: ['partnership', 'email', 'followup', 'owner'],
    related_use_case_path: '/use-cases/partnership-announcement',
    subject: 'Who owns enablement for the {{partner}} rollout at {{company}}?',
    notes: 'Day 5 follow-up; owner routing question.',
    body:
      'Hi {{name}} — quick question so I reach the right person.\n\nFor the {{partner}} rollout at {{company}}, who owns enablement/templates and the messaging standard — your team or {{alt_owner}}?\n\nIf you point me to the owner, I’ll send:\n- the rollout checklist (ownership map + enablement + reporting)\n- 2 copy examples tied to {{handoff}} and {{metric}}\n- a simple “don’t send” rule so reps don’t invent context mid-rollout\n\nIf it’s you, are you open to a quick 12-minute call to confirm what “good” looks like for {{metric}} during the rollout?',
  }),
  t({
    id: 'partnership-linkedin-1-ultra-short',
    slug: 'partnership-linkedin-1-ultra-short',
    trigger: 'partnership',
    channel: 'linkedin',
    persona: 'sdr_ae',
    length: 'ultra_short',
    title: 'Partnership — LinkedIn DM #1 (ultra short)',
    tags: ['partnership', 'linkedin', 'dm', 'ultra_short'],
    related_use_case_path: '/use-cases/partnership-announcement',
    subject: null,
    notes: 'One question: stage + owner.',
    body:
      'Congrats on {{partner}} — are you in {{stage}} right now, and who owns {{handoff}} for {{company}}?',
  }),
  t({
    id: 'partnership-linkedin-2-value',
    slug: 'partnership-linkedin-2-value',
    trigger: 'partnership',
    channel: 'linkedin',
    persona: 'sdr_ae',
    length: 'value',
    title: 'Partnership — LinkedIn DM #2 (value + question)',
    tags: ['partnership', 'linkedin', 'dm', 'value'],
    related_use_case_path: '/use-cases/partnership-announcement',
    subject: null,
    notes: 'Offer the rollout checklist; ask permission.',
    body:
      'Partnership rollouts usually break handoffs + messaging consistency.\n\nIf {{company}} is rolling out with {{partner}}, I can share a short checklist for ownership + reporting + enablement (including copy tied to {{handoff}}).\n\nWant it?',
  }),
  t({
    id: 'partnership-linkedin-followup',
    slug: 'partnership-linkedin-followup',
    trigger: 'partnership',
    channel: 'linkedin',
    persona: 'sdr_ae',
    length: 'followup',
    title: 'Partnership — LinkedIn DM follow-up',
    tags: ['partnership', 'linkedin', 'dm', 'followup'],
    related_use_case_path: '/use-cases/partnership-announcement',
    subject: null,
    notes: 'Owner routing follow-up.',
    body:
      'Quick follow-up: who owns enablement/templates for the {{partner}} rollout at {{company}}—you or {{alt_owner}}?\n\nIf you point me to the owner, I’ll send the checklist + examples tied to {{metric}}.',
  }),
  t({
    id: 'partnership-call-1-opener',
    slug: 'partnership-call-1-opener',
    trigger: 'partnership',
    channel: 'call',
    persona: 'sdr_ae',
    length: 'opener',
    title: 'Partnership — call opener #1',
    tags: ['partnership', 'call', 'opener'],
    related_use_case_path: '/use-cases/partnership-announcement',
    subject: null,
    notes: 'Qualify stage + handoff owner.',
    body:
      'Hey {{name}} — quick question on the {{partner}} rollout at {{company}}. Are you in {{stage}} right now, and who owns {{handoff}} between {{system_a}} and {{system_b}}? I’m asking because rollout friction usually shows up there first.',
  }),
  t({
    id: 'partnership-call-2-opener',
    slug: 'partnership-call-2-opener',
    trigger: 'partnership',
    channel: 'call',
    persona: 'sdr_ae',
    length: 'opener',
    title: 'Partnership — call opener #2',
    tags: ['partnership', 'call', 'opener', 'owner'],
    related_use_case_path: '/use-cases/partnership-announcement',
    subject: null,
    notes: 'Owner routing + artifact offer.',
    body:
      'Hi {{name}} — quick routing question: who owns enablement/templates for the {{partner}} rollout at {{company}}—you or {{alt_owner}}? I can send a short checklist and 2 copy examples tied to {{handoff}} and {{metric}}.',
  }),

  // Product launch (10)
  t({
    id: 'product-launch-email-1-short',
    slug: 'product-launch-email-1-short',
    trigger: 'product_launch',
    channel: 'email',
    persona: 'sdr_ae',
    length: 'short',
    title: 'Product launch — email #1 (short)',
    tags: ['product_launch', 'email', 'cold', 'post_launch'],
    related_use_case_path: '/use-cases/product-launch-timing',
    subject: 'Quick question post-launch at {{company}}',
    notes: 'Best right after a launch when teams are fixing friction and updating messaging.',
    body:
      'Hi {{name}} — congrats on the launch at {{company}}.\n\nPost-launch, teams usually do two things at once: reduce friction and scale outbound. That’s when prioritization and messaging consistency matter—reps need a clear “why now” tied to the launch without inventing facts.\n\nIf {{initiative}} is a focus in the next {{timeframe}}, I can share a short playbook: signals to watch, a daily shortlist tied to {{metric}}, and a tokenized draft your team can use immediately.\n\nWorth a 12-minute call, or should I ask {{alt_owner}}?',
  }),
  t({
    id: 'product-launch-email-2-medium',
    slug: 'product-launch-email-2-medium',
    trigger: 'product_launch',
    channel: 'email',
    persona: 'sdr_ae',
    length: 'medium',
    title: 'Product launch — email #2 (medium)',
    tags: ['product_launch', 'email', 'cold', 'enablement'],
    related_use_case_path: '/use-cases/product-launch-timing',
    subject: 'A simple post-launch workflow to improve {{metric}}',
    notes: 'Use when you want to describe the week-1 workflow in practical steps.',
    body:
      'Hi {{name}} — after a launch, outbound usually becomes a “do more with less time” problem.\n\nTeams that win the first 30 days post-launch do three things consistently:\n1) decide what triggers count as “why now” (launch, partnerships, hiring, displacement)\n2) prioritize accounts daily instead of running a backlog\n3) standardize first-touch messaging so the team doesn’t drift\n\nIf {{company}} is pushing {{initiative}} right now, I can share the exact checklist + copy pattern we use: a one-line why-now, one concrete next step, and tokens ({{company}}, {{trigger_event}}, {{initiative}}) so it stays truthful.\n\nOpen to a quick 15-minute walkthrough this week?',
  }),
  t({
    id: 'product-launch-email-3-breakup',
    slug: 'product-launch-email-3-breakup',
    trigger: 'product_launch',
    channel: 'email',
    persona: 'sdr_ae',
    length: 'breakup',
    title: 'Product launch — email #3 (breakup)',
    tags: ['product_launch', 'email', 'breakup'],
    related_use_case_path: '/use-cases/product-launch-timing',
    subject: 'Close the loop for {{company}}?',
    notes: 'Use as a final touch when there is no response.',
    body:
      'Hi {{name}} — closing the loop.\n\nI reached out because immediately after a launch, teams often rework {{initiative}} and outbound messaging. The timing window is short, and the risk is sending generic “congrats” notes that don’t convert.\n\nThe teams that do well post-launch usually align on three things quickly:\n- what counts as a real “why now” signal\n- which accounts to prioritize first\n- one message pattern that stays consistent across reps\n\nIf this isn’t a priority at {{company}} in the next {{timeframe}}, no problem — I can close this out.\n\nIf it is, would you prefer I send the one-page checklist + examples, or are you open to a quick 12-minute call with the owner for {{metric}}?',
  }),
  t({
    id: 'product-launch-email-followup-1',
    slug: 'product-launch-email-followup-1',
    trigger: 'product_launch',
    channel: 'email',
    persona: 'sdr_ae',
    length: 'followup',
    title: 'Product launch — email follow-up #1 (value)',
    tags: ['product_launch', 'email', 'followup', 'value'],
    related_use_case_path: '/use-cases/product-launch-timing',
    subject: 'One-page post-launch outreach checklist',
    notes: 'Day 2 follow-up; sends an artifact.',
    body:
      'Hi {{name}} — following up with a quick artifact.\n\nI can send a one-page “post-launch outreach” checklist that includes:\n- how to write a truthful why-now tied to {{trigger_event}}\n- how to pick accounts to contact (daily shortlist)\n- 2 message patterns that improve {{metric}} without over-personalizing\n- a simple “don’t send” rule so reps don’t invent context\n\nIf {{initiative}} is a priority for {{company}} this quarter, it should be useful.\n\nIf you want it, I can send it here — or if you’re open to a quick 12-minute call, I’ll tailor the checklist to the messaging standards you want post-launch. Which is easier?',
  }),
  t({
    id: 'product-launch-email-followup-2',
    slug: 'product-launch-email-followup-2',
    trigger: 'product_launch',
    channel: 'email',
    persona: 'sdr_ae',
    length: 'followup',
    title: 'Product launch — email follow-up #2 (tight ask)',
    tags: ['product_launch', 'email', 'followup', 'owner'],
    related_use_case_path: '/use-cases/product-launch-timing',
    subject: 'Who owns outbound enablement at {{company}} post-launch?',
    notes: 'Day 5 follow-up; owner routing question.',
    body:
      'Hi {{name}} — quick routing question.\n\nPost-launch, who owns outbound enablement and the messaging standard at {{company}} — you or {{alt_owner}}?\n\nIf you point me to the owner, I’ll send:\n- the one-page checklist (signals → shortlist → draft)\n- 2 copy examples tied to {{initiative}} and {{metric}}\n- the “stop rules” (when not to send because context is missing)\n\nIf it’s you, are you open to a quick 12-minute call to confirm what success looks like for {{metric}} over the next {{timeframe}}?',
  }),
  t({
    id: 'product-launch-linkedin-1-ultra-short',
    slug: 'product-launch-linkedin-1-ultra-short',
    trigger: 'product_launch',
    channel: 'linkedin',
    persona: 'sdr_ae',
    length: 'ultra_short',
    title: 'Product launch — LinkedIn DM #1 (ultra short)',
    tags: ['product_launch', 'linkedin', 'dm', 'ultra_short'],
    related_use_case_path: '/use-cases/product-launch-timing',
    subject: null,
    notes: 'One question. Keep it crisp.',
    body:
      'Congrats on the launch at {{company}} — what’s the priority in the next {{timeframe}}: {{initiative}} or {{alt_initiative}}?',
  }),
  t({
    id: 'product-launch-linkedin-2-value',
    slug: 'product-launch-linkedin-2-value',
    trigger: 'product_launch',
    channel: 'linkedin',
    persona: 'sdr_ae',
    length: 'value',
    title: 'Product launch — LinkedIn DM #2 (value + question)',
    tags: ['product_launch', 'linkedin', 'dm', 'value'],
    related_use_case_path: '/use-cases/product-launch-timing',
    subject: null,
    notes: 'Offer the checklist; ask permission.',
    body:
      'Post-launch, teams usually fix friction + standardize messaging.\n\nIf {{company}} is focused on {{initiative}}, I can share a one-page checklist: signals to watch, how to prioritize daily, and a tokenized draft tied to {{metric}}.\n\nWant it?',
  }),
  t({
    id: 'product-launch-linkedin-followup',
    slug: 'product-launch-linkedin-followup',
    trigger: 'product_launch',
    channel: 'linkedin',
    persona: 'sdr_ae',
    length: 'followup',
    title: 'Product launch — LinkedIn DM follow-up',
    tags: ['product_launch', 'linkedin', 'dm', 'followup'],
    related_use_case_path: '/use-cases/product-launch-timing',
    subject: null,
    notes: 'Owner routing follow-up.',
    body:
      'Quick follow-up: who owns outbound enablement for {{initiative}} at {{company}}—you or {{alt_owner}}?\n\nIf you point me to the owner, I’ll send the checklist + examples tied to {{metric}}.',
  }),
  t({
    id: 'product-launch-call-1-opener',
    slug: 'product-launch-call-1-opener',
    trigger: 'product_launch',
    channel: 'call',
    persona: 'sdr_ae',
    length: 'opener',
    title: 'Product launch — call opener #1',
    tags: ['product_launch', 'call', 'opener'],
    related_use_case_path: '/use-cases/product-launch-timing',
    subject: null,
    notes: 'Qualify priority fast.',
    body:
      'Hey {{name}} — congrats on the launch at {{company}}. I’m calling because post-launch teams usually prioritize one initiative first. Quick question: is the focus in the next {{timeframe}} {{initiative}}, or something else?',
  }),
  t({
    id: 'product-launch-call-2-opener',
    slug: 'product-launch-call-2-opener',
    trigger: 'product_launch',
    channel: 'call',
    persona: 'sdr_ae',
    length: 'opener',
    title: 'Product launch — call opener #2',
    tags: ['product_launch', 'call', 'opener', 'owner'],
    related_use_case_path: '/use-cases/product-launch-timing',
    subject: null,
    notes: 'Use when you need to route to the enablement owner post-launch without pitching.',
    body:
      'Hi {{name}} — quick routing question. Post-launch, who owns outbound enablement and the messaging standard for {{initiative}} at {{company}}—you or {{alt_owner}}? I can send a one-page checklist tied to {{metric}}.',
  }),

  // Competitive displacement (10)
  t({
    id: 'competitive-displacement-email-1-short',
    slug: 'competitive-displacement-email-1-short',
    trigger: 'competitive_displacement',
    channel: 'email',
    persona: 'sdr_ae',
    length: 'short',
    title: 'Competitive displacement — email #1 (short)',
    tags: ['competitive_displacement', 'email', 'cold', 'checklist'],
    related_use_case_path: '/use-cases/competitive-displacement',
    subject: 'Evaluation checklist if you’re rethinking {{vendor}}',
    notes: 'Best when a buyer is actively evaluating alternatives; lead with a neutral checklist.',
    body:
      'Hi {{name}} — quick note.\n\nWhen teams reconsider {{vendor}}, the risk isn’t picking the “best feature”—it’s picking something that fails in rollout and reporting.\n\nIf you’re evaluating options for {{workflow}} at {{company}}, I can share a one-page checklist that covers:\n- success criteria (what “good” means)\n- rollout risk (who adopts, how quickly)\n- reporting + maintenance (what breaks over time)\n\nIf it’s useful, I’ll send it. Worth a quick 12-minute call, or should I route it to {{alt_owner}}?',
  }),
  t({
    id: 'competitive-displacement-email-2-medium',
    slug: 'competitive-displacement-email-2-medium',
    trigger: 'competitive_displacement',
    channel: 'email',
    persona: 'sdr_ae',
    length: 'medium',
    title: 'Competitive displacement — email #2 (medium)',
    tags: ['competitive_displacement', 'email', 'cold', 'pilot'],
    related_use_case_path: '/use-cases/competitive-displacement',
    subject: 'Shortlist → pilot decision points for {{workflow}}',
    notes: 'Use when the buyer is moving from research to pilot.',
    body:
      'Hi {{name}} — if you’re moving from research → shortlist → pilot for {{workflow}}, the fastest way to avoid churn later is to agree on the decision points early.\n\nMost teams get stuck because:\n- different stakeholders want different outcomes\n- rollout complexity is underestimated\n- reporting requirements are discovered late\n\nIf {{company}} is re-evaluating {{vendor}}, I can send:\n1) a pilot plan (what to test in week 1)\n2) an evaluation checklist (criteria + rollout risk + reporting)\n3) a simple messaging standard so reps don’t drift while the decision is made\n\nOpen to a quick 15-minute call to sanity-check your criteria?',
  }),
  t({
    id: 'competitive-displacement-email-3-breakup',
    slug: 'competitive-displacement-email-3-breakup',
    trigger: 'competitive_displacement',
    channel: 'email',
    persona: 'sdr_ae',
    length: 'breakup',
    title: 'Competitive displacement — email #3 (breakup)',
    tags: ['competitive_displacement', 'email', 'breakup'],
    related_use_case_path: '/use-cases/competitive-displacement',
    subject: 'Close the loop on {{vendor}} evaluation?',
    notes: 'Use when the evaluation is not active or timing is unclear.',
    body:
      'Hi {{name}} — quick close-the-loop.\n\nI reached out because when teams evaluate alternatives to {{vendor}}, it helps to standardize criteria early (success, rollout, reporting) so the pilot doesn’t drift.\n\nWhat usually goes wrong isn’t intent — it’s ambiguity:\n- stakeholders optimize for different outcomes\n- rollout risk gets discovered late\n- reporting requirements show up after the pilot “worked”\n\nIf {{workflow}} evaluation isn’t active at {{company}} right now, no problem — I can close this out and circle back later.\n\nIf it is active, would you prefer I send the checklist + pilot plan, or are you open to a quick 12-minute call with the owner for {{metric}} to align on decision points?',
  }),
  t({
    id: 'competitive-displacement-email-followup-1',
    slug: 'competitive-displacement-email-followup-1',
    trigger: 'competitive_displacement',
    channel: 'email',
    persona: 'sdr_ae',
    length: 'followup',
    title: 'Competitive displacement — email follow-up #1 (value)',
    tags: ['competitive_displacement', 'email', 'followup', 'value'],
    related_use_case_path: '/use-cases/competitive-displacement',
    subject: 'One-page checklist: success + rollout + reporting',
    notes: 'Day 2; offers checklist without pitching.',
    body:
      'Hi {{name}} — following up with something useful.\n\nIf {{company}} is evaluating alternatives to {{vendor}} for {{workflow}}, I can send a one-page checklist that includes:\n- 6 success criteria questions\n- rollout risk checklist (adoption + enablement)\n- reporting and maintenance requirements\n- a simple week-1 pilot plan (what to test first)\n\nIt’s designed to keep the decision neutral and prevent “pilot drift.”\n\nIf you want it, I can send it here — or if you’re open to a quick 12-minute call, I’ll tailor the checklist to the metrics you care about most (like {{metric}}). Which is easier?',
  }),
  t({
    id: 'competitive-displacement-email-followup-2',
    slug: 'competitive-displacement-email-followup-2',
    trigger: 'competitive_displacement',
    channel: 'email',
    persona: 'sdr_ae',
    length: 'followup',
    title: 'Competitive displacement — email follow-up #2 (tight ask)',
    tags: ['competitive_displacement', 'email', 'followup', 'owner'],
    related_use_case_path: '/use-cases/competitive-displacement',
    subject: 'Who owns {{workflow}} evaluation at {{company}}?',
    notes: 'Day 5; owner routing question.',
    body:
      'Hi {{name}} — quick question so I reach the right person.\n\nWho owns the evaluation for {{workflow}} at {{company}} — you or {{alt_owner}}?\n\nIf you point me to the owner, I’ll send:\n- the checklist (success + rollout + reporting)\n- a week-1 pilot plan\n- “decision points” (what must be true to proceed)\n- the “stop rules” so messaging doesn’t drift mid-evaluation\n\nIf it’s you, are you open to a quick 12-minute call to confirm how you’ll measure {{metric}} during the transition?',
  }),
  t({
    id: 'competitive-displacement-linkedin-1-ultra-short',
    slug: 'competitive-displacement-linkedin-1-ultra-short',
    trigger: 'competitive_displacement',
    channel: 'linkedin',
    persona: 'sdr_ae',
    length: 'ultra_short',
    title: 'Competitive displacement — LinkedIn DM #1 (ultra short)',
    tags: ['competitive_displacement', 'linkedin', 'dm', 'ultra_short'],
    related_use_case_path: '/use-cases/competitive-displacement',
    subject: null,
    notes: 'Use when you want to confirm evaluation is active before sending anything else.',
    body:
      'Quick question: are you actively evaluating alternatives to {{vendor}} for {{workflow}} at {{company}}?',
  }),
  t({
    id: 'competitive-displacement-linkedin-2-value',
    slug: 'competitive-displacement-linkedin-2-value',
    trigger: 'competitive_displacement',
    channel: 'linkedin',
    persona: 'sdr_ae',
    length: 'value',
    title: 'Competitive displacement — LinkedIn DM #2 (value + question)',
    tags: ['competitive_displacement', 'linkedin', 'dm', 'value'],
    related_use_case_path: '/use-cases/competitive-displacement',
    subject: null,
    notes: 'Offer the neutral checklist.',
    body:
      'If you’re evaluating alternatives to {{vendor}}, I can share a neutral one-page checklist (success criteria + rollout risk + reporting) for {{workflow}}.\n\nWant it?',
  }),
  t({
    id: 'competitive-displacement-linkedin-followup',
    slug: 'competitive-displacement-linkedin-followup',
    trigger: 'competitive_displacement',
    channel: 'linkedin',
    persona: 'sdr_ae',
    length: 'followup',
    title: 'Competitive displacement — LinkedIn DM follow-up',
    tags: ['competitive_displacement', 'linkedin', 'dm', 'followup'],
    related_use_case_path: '/use-cases/competitive-displacement',
    subject: null,
    notes: 'Owner routing follow-up.',
    body:
      'Who owns the evaluation for {{workflow}} at {{company}}—you or {{alt_owner}}?\n\nIf you point me to the owner, I’ll send the checklist + pilot plan tied to {{metric}}.',
  }),
  t({
    id: 'competitive-displacement-call-1-opener',
    slug: 'competitive-displacement-call-1-opener',
    trigger: 'competitive_displacement',
    channel: 'call',
    persona: 'sdr_ae',
    length: 'opener',
    title: 'Competitive displacement — call opener #1',
    tags: ['competitive_displacement', 'call', 'opener'],
    related_use_case_path: '/use-cases/competitive-displacement',
    subject: null,
    notes: 'Qualify evaluation status.',
    body:
      'Hey {{name}} — quick question: are you actively evaluating alternatives to {{vendor}} for {{workflow}} at {{company}} right now, or is it earlier-stage research?',
  }),
  t({
    id: 'competitive-displacement-call-2-opener',
    slug: 'competitive-displacement-call-2-opener',
    trigger: 'competitive_displacement',
    channel: 'call',
    persona: 'sdr_ae',
    length: 'opener',
    title: 'Competitive displacement — call opener #2',
    tags: ['competitive_displacement', 'call', 'opener', 'owner'],
    related_use_case_path: '/use-cases/competitive-displacement',
    subject: null,
    notes: 'Use to route to the evaluation owner without pitching; keeps it neutral.',
    body:
      'Hi {{name}} — quick routing question. Who owns the evaluation for {{workflow}} at {{company}}—you or {{alt_owner}}? I can send a neutral checklist and pilot plan tied to {{metric}}.',
  }),

  // Expansion (10)
  t({
    id: 'expansion-email-1-short',
    slug: 'expansion-email-1-short',
    trigger: 'expansion',
    channel: 'email',
    persona: 'sdr_ae',
    length: 'short',
    title: 'Expansion — email #1 (short)',
    tags: ['expansion', 'email', 'cold', 'why_now'],
    related_use_case_path: '/use-cases/expansion-signals',
    subject: 'Quick question on expansion into {{region_or_segment}}',
    notes: 'Best when expansion implies new processes, segmentation, and messaging changes.',
    body:
      'Hi {{name}} — congrats on expanding into {{region_or_segment}}.\n\nExpansion usually breaks one thing first: consistent execution. New reps/segments mean routing changes, messaging drift, and a growing backlog of “accounts we should contact.”\n\nIf {{initiative}} is a focus for {{company}} in the next {{timeframe}}, I can share a playbook: the signals to watch for your watchlist, a daily shortlist tied to {{metric}}, and tokenized drafts so reps can move fast without inventing context.\n\nWorth a 12-minute call, or should I ask {{alt_owner}}?',
  }),
  t({
    id: 'expansion-email-2-medium',
    slug: 'expansion-email-2-medium',
    trigger: 'expansion',
    channel: 'email',
    persona: 'sdr_ae',
    length: 'medium',
    title: 'Expansion — email #2 (medium)',
    tags: ['expansion', 'email', 'cold', 'enablement'],
    related_use_case_path: '/use-cases/expansion-signals',
    subject: 'Expansion exposes one bottleneck—fast',
    notes: 'Use when you want to lead with operational bottlenecks and a week-1 plan.',
    body:
      'Hi {{name}} — expansion into {{region_or_segment}} usually creates a predictable pattern.\n\nAs the org scales, one bottleneck shows up early:\n- handoffs (who owns which accounts)\n- enablement (what messaging stays consistent)\n- reporting (what “good” means for {{metric}})\n\nIf {{company}} is working on {{initiative}} during expansion, the best week-1 workflow is:\n1) define ICP + segments\n2) keep a watchlist of target accounts\n3) alert on timing signals\n4) generate a daily shortlist with reasons\n5) use tokenized drafts to keep messaging consistent across teams\n\nOpen to a quick 15-minute walkthrough? I can tailor the checklist to your motion.',
  }),
  t({
    id: 'expansion-email-3-breakup',
    slug: 'expansion-email-3-breakup',
    trigger: 'expansion',
    channel: 'email',
    persona: 'sdr_ae',
    length: 'breakup',
    title: 'Expansion — email #3 (breakup)',
    tags: ['expansion', 'email', 'breakup'],
    related_use_case_path: '/use-cases/expansion-signals',
    subject: 'Close the loop for {{company}}?',
    notes: 'Use when expansion execution isn’t active.',
    body:
      'Hi {{name}} — quick close-the-loop.\n\nI reached out because expansion into {{region_or_segment}} usually forces a decision on {{initiative}} and the messaging standard.\n\nThe common failure mode is predictable: teams keep the same targeting + copy while segments change, so reps either over-personalize (slow) or go generic (low conversion).\n\nIf that’s not a priority for {{company}} in the next {{timeframe}}, no problem — I can close this out.\n\nIf it is a priority, would you prefer I send the one-page checklist + examples, or are you open to a quick 12-minute call with the owner for {{metric}} to align on what “good” looks like during expansion?',
  }),
  t({
    id: 'expansion-email-followup-1',
    slug: 'expansion-email-followup-1',
    trigger: 'expansion',
    channel: 'email',
    persona: 'sdr_ae',
    length: 'followup',
    title: 'Expansion — email follow-up #1 (value)',
    tags: ['expansion', 'email', 'followup', 'value'],
    related_use_case_path: '/use-cases/expansion-signals',
    subject: 'One-page expansion execution checklist',
    notes: 'Day 2 follow-up; artifact offer.',
    body:
      'Hi {{name}} — sharing a quick artifact.\n\nI can send a one-page “expansion execution” checklist that covers:\n- what signals to watch on target accounts (so timing stays real)\n- how to prioritize daily during expansion\n- how to keep messaging consistent (tokenized drafts) as segments change\n- a simple “don’t send” rule when context is missing\n\nIf {{company}} is focusing on {{initiative}} while expanding into {{region_or_segment}}, it should help.\n\nIf you want it, I can send it here — or if you’re open to a quick 12-minute call, I’ll tailor it to how you’re measuring {{metric}} across segments. Which is easier?',
  }),
  t({
    id: 'expansion-email-followup-2',
    slug: 'expansion-email-followup-2',
    trigger: 'expansion',
    channel: 'email',
    persona: 'sdr_ae',
    length: 'followup',
    title: 'Expansion — email follow-up #2 (tight ask)',
    tags: ['expansion', 'email', 'followup', 'owner'],
    related_use_case_path: '/use-cases/expansion-signals',
    subject: 'Who owns {{initiative}} during expansion at {{company}}?',
    notes: 'Day 5 follow-up; owner routing.',
    body:
      'Hi {{name}} — quick routing question.\n\nDuring expansion into {{region_or_segment}}, who owns execution for {{initiative}} at {{company}} — you or {{alt_owner}}?\n\nIf you point me to the owner, I’ll send:\n- the checklist (signals + daily prioritization)\n- 2 copy examples tied to {{metric}}\n- a simple guardrail so reps don’t reuse copy when segments change\n\nIf it’s you, are you open to a quick 12-minute call to confirm what you’re optimizing for over the next {{timeframe}}?',
  }),
  t({
    id: 'expansion-linkedin-1-ultra-short',
    slug: 'expansion-linkedin-1-ultra-short',
    trigger: 'expansion',
    channel: 'linkedin',
    persona: 'sdr_ae',
    length: 'ultra_short',
    title: 'Expansion — LinkedIn DM #1 (ultra short)',
    tags: ['expansion', 'linkedin', 'dm', 'ultra_short'],
    related_use_case_path: '/use-cases/expansion-signals',
    subject: null,
    notes: 'Use to confirm the expansion priority before sending a longer note.',
    body:
      'Congrats on expansion into {{region_or_segment}} — is the priority in the next {{timeframe}} {{initiative}} or {{alt_initiative}} for {{company}}?',
  }),
  t({
    id: 'expansion-linkedin-2-value',
    slug: 'expansion-linkedin-2-value',
    trigger: 'expansion',
    channel: 'linkedin',
    persona: 'sdr_ae',
    length: 'value',
    title: 'Expansion — LinkedIn DM #2 (value + question)',
    tags: ['expansion', 'linkedin', 'dm', 'value'],
    related_use_case_path: '/use-cases/expansion-signals',
    subject: null,
    notes: 'Offer the expansion execution checklist and ask permission to send it.',
    body:
      'Expansion usually breaks messaging consistency + reporting first.\n\nIf {{company}} is focused on {{initiative}} while expanding into {{region_or_segment}}, I can share a one-page checklist: signals to watch, daily prioritization, and tokenized drafts tied to {{metric}}.\n\nWant it?',
  }),
  t({
    id: 'expansion-linkedin-followup',
    slug: 'expansion-linkedin-followup',
    trigger: 'expansion',
    channel: 'linkedin',
    persona: 'sdr_ae',
    length: 'followup',
    title: 'Expansion — LinkedIn DM follow-up',
    tags: ['expansion', 'linkedin', 'dm', 'followup'],
    related_use_case_path: '/use-cases/expansion-signals',
    subject: null,
    notes: 'Owner routing follow-up.',
    body:
      'Quick follow-up: who owns execution for {{initiative}} at {{company}} during expansion—your team or {{alt_owner}}?\n\nIf you point me to the owner, I’ll send the checklist + examples tied to {{metric}}.',
  }),
  t({
    id: 'expansion-call-1-opener',
    slug: 'expansion-call-1-opener',
    trigger: 'expansion',
    channel: 'call',
    persona: 'sdr_ae',
    length: 'opener',
    title: 'Expansion — call opener #1',
    tags: ['expansion', 'call', 'opener'],
    related_use_case_path: '/use-cases/expansion-signals',
    subject: null,
    notes: 'Qualify priority + timing.',
    body:
      'Hey {{name}} — congrats on expansion into {{region_or_segment}}. Quick question: in the next {{timeframe}}, is the priority {{initiative}}, or is it something else? I’m asking because expansion usually forces a decision on messaging and execution quickly.',
  }),
  t({
    id: 'expansion-call-2-opener',
    slug: 'expansion-call-2-opener',
    trigger: 'expansion',
    channel: 'call',
    persona: 'sdr_ae',
    length: 'opener',
    title: 'Expansion — call opener #2',
    tags: ['expansion', 'call', 'opener', 'owner'],
    related_use_case_path: '/use-cases/expansion-signals',
    subject: null,
    notes: 'Use to route to the initiative owner during expansion without pitching.',
    body:
      'Hi {{name}} — quick routing question. Who owns execution for {{initiative}} at {{company}} during expansion into {{region_or_segment}}—you or {{alt_owner}}? I can send a one-page checklist tied to {{metric}}.',
  }),
]

export function getTemplateBySlug(slug: string): OutreachTemplate | null {
  const s = slug.trim().toLowerCase()
  return TEMPLATE_LIBRARY.find((x) => x.slug === s) ?? null
}

export function getTokenGlossaryForTemplate(template: OutreachTemplate): TemplateTokenDef[] {
  const set = new Set(template.tokens.map((t) => t.toLowerCase()))
  return TEMPLATE_TOKENS.filter((d) => set.has(d.token.toLowerCase()))
}

